import { useState } from "react";
import { createPortal } from "react-dom";
import { motion } from "framer-motion";
import { ScheduleEvent } from "@/types";
import { useLanguage } from "@/contexts/LanguageContext";
import { cn } from "@/lib/utils";
import { zenTap } from "@/lib/animationUtils";
import { useModalA11y } from "@/hooks/useModalA11y";
import { getEventColor } from "./constants";

// Premium Event Details Modal
export function EventDetailsModal({
  event,
  onClose,
  onDelete,
}: {
  event: ScheduleEvent;
  onClose: () => void;
  onDelete?: () => void;
}) {
  const { t, language } = useLanguage();
  const { modalRef, handleKeyDown } = useModalA11y(true, onClose);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const isHabitEvent = event.source === "habit";
  const isTaskEvent = event.source === "task";
  const isAutoGenerated = event.isAutoGenerated;
  const eventColor = getEventColor(event.colorVar, event.urgent);
  const eventTimeFormatter = new Intl.DateTimeFormat(language, {
    hour: "2-digit",
    minute: "2-digit",
  });

  const formatTime = (hour: number, minute: number) =>
    eventTimeFormatter.format(new Date(2000, 0, 1, hour, minute));

  const modal = (
    <motion.div
      ref={modalRef}
      onKeyDown={handleKeyDown}
      role="dialog"
      aria-modal="true"
      aria-labelledby="event-details-title"
      className="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center overflow-y-auto overscroll-contain ps-[max(1rem,var(--safe-inline-start))] pe-[max(1rem,var(--safe-inline-end))] pb-[max(1rem,var(--safe-bottom))] pt-[max(1rem,var(--safe-top))]"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
    >
      {/* Backdrop */}
      <motion.div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      />

      {/* Modal content */}
      <motion.div
        className="relative max-h-[calc(100dvh-var(--safe-top)-var(--safe-bottom)-2rem)] w-full max-w-xs overflow-x-hidden overflow-y-auto overscroll-contain rounded-3xl border border-border/60 bg-card text-card-foreground shadow-xl"
        initial={{ opacity: 0, scale: 0.9, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.9, y: 20 }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-5">
          <div className="text-center mb-4">
            <div
              aria-hidden="true"
              className="relative mx-auto mb-3 flex h-16 w-16 items-center justify-center rounded-2xl border-2 bg-muted text-3xl"
              style={{ borderColor: eventColor }}
            >
              <span>{event.emoji}</span>

              {isHabitEvent && (
                <span className="absolute -top-1 -end-1 text-sm bg-primary rounded-full w-6 h-6 flex items-center justify-center">
                  🎯
                </span>
              )}
              {isTaskEvent && (
                <span className="absolute -top-1 -end-1 text-sm bg-primary rounded-full w-6 h-6 flex items-center justify-center">
                  📋
                </span>
              )}
            </div>

            <h3
              id="event-details-title"
              className="whitespace-normal [overflow-wrap:anywhere] text-lg font-bold text-slate-800 dark:text-white"
            >
              <bdi dir="auto">{event.title}</bdi>
            </h3>
            <p className="text-sm text-slate-500 dark:text-white/60">
              <time>{formatTime(event.startHour, event.startMinute)}</time>
              {"–"}
              <time>{formatTime(event.endHour, event.endMinute)}</time>
            </p>

            {isHabitEvent && (
              <div className="mt-2 px-3 py-1.5 bg-primary/20 rounded-full inline-flex items-center gap-1.5">
                <span>🎯</span>
                <span className="text-xs text-primary font-medium">
                  {t.habitReminder || "Habit Reminder"}
                </span>
              </div>
            )}

            {isTaskEvent && (
              <div className="mt-2 px-3 py-1.5 bg-primary/20 rounded-full inline-flex items-center gap-1.5">
                <span>📋</span>
                <span className="text-xs text-primary font-medium">
                  {t.autoScheduled || "Auto-scheduled"}
                </span>
              </div>
            )}
          </div>

          {event.note && (
            <div className="mb-4 p-3 bg-secondary backdrop-blur-sm rounded-xl border border-border">
              <bdi dir="auto" className="block whitespace-pre-wrap text-sm text-foreground [overflow-wrap:anywhere]">
                {event.note}
              </bdi>
            </div>
          )}

          {isHabitEvent && (
            <div className="mb-4 p-3 bg-green-500/10 rounded-xl border border-green-500/20">
              <p className="break-words hyphens-manual text-xs text-green-400">
                {t.habitEventExplanation ||
                  "This event is from your habit. Edit the habit to change it."}
              </p>
            </div>
          )}

          {isTaskEvent && (
            <div className="mb-4 p-3 bg-primary/10 rounded-xl border border-primary/20">
              <p className="break-words hyphens-manual text-xs text-primary">
                {t.taskEventExplanation ||
                  "This block is auto-generated from your tasks. Complete the task to remove it."}
              </p>
            </div>
          )}

          <div className="flex flex-col gap-2 min-[360px]:flex-row">
            <motion.button
              onClick={onClose}
              whileHover={{ scale: 1.02 }}
              whileTap={zenTap.card}
              className="min-h-[44px] h-auto min-w-0 flex-1 whitespace-normal break-words hyphens-manual rounded-xl border border-border bg-secondary py-3 font-medium text-slate-800 backdrop-blur-sm dark:text-white"
            >
              {t.close || "Close"}
            </motion.button>

            {onDelete &&
              !isHabitEvent &&
              !isAutoGenerated &&
              (showDeleteConfirm ? (
                <motion.button
                  onClick={() => {
                    if (isDeleting) return;
                    setIsDeleting(true);
                    onDelete();
                  }}
                  disabled={isDeleting}
                  whileHover={{ scale: 1.02 }}
                  whileTap={zenTap.card}
                  className={cn(
                    "min-h-[44px] h-auto min-w-0 flex-1 whitespace-normal break-words hyphens-manual rounded-xl border border-red-500/40 bg-red-500/30 py-3 font-medium text-red-300",
                    isDeleting && "opacity-50",
                  )}
                >
                  {t.confirmDelete || "Confirm?"}
                </motion.button>
              ) : (
                <motion.button
                  onClick={() => setShowDeleteConfirm(true)}
                  whileHover={{ scale: 1.02 }}
                  whileTap={zenTap.card}
                  className="min-h-[44px] h-auto min-w-0 flex-1 whitespace-normal break-words hyphens-manual rounded-xl border border-red-500/30 bg-red-500/20 py-3 font-medium text-red-400"
                >
                  {t.delete || "Delete"}
                </motion.button>
              ))}
          </div>
        </div>
      </motion.div>
    </motion.div>
  );

  return typeof document === "undefined" ? modal : createPortal(modal, document.body);
}
