import { useState } from "react";
import { createPortal } from "react-dom";
import { motion } from "framer-motion";
import { CheckCircle2, ListChecks, Target } from "lucide-react";
import { ScheduleEvent } from "@/types";
import { useLanguage } from "@/contexts/LanguageContext";
import { cn } from "@/lib/utils";
import { zenTap } from "@/lib/animationUtils";
import { useModalA11y } from "@/hooks/useModalA11y";
import { useBackHandler } from "@/hooks/useBackHandler";
import { ParticleBackground } from "@/components/stats";
import { getEventGradient } from "./constants";
import { useShouldAnimate } from "@/hooks/useShouldAnimate";
import { formatLocalizedTime } from "@/lib/timeUtils";

// Premium Event Details Modal
export function EventDetailsModal({
  event,
  onClose,
  onDelete,
  forceDark = false,
}: {
  event: ScheduleEvent;
  onClose: () => void;
  onDelete?: () => void;
  forceDark?: boolean;
}) {
  const { t, language } = useLanguage();
  const shouldAnimate = useShouldAnimate();
  const { modalRef, handleKeyDown } = useModalA11y(true, onClose);
  useBackHandler(true, onClose);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const isHabitEvent = event.source === "habit";
  const isTaskEvent = event.source === "task";
  const isAutoGenerated = event.isAutoGenerated;
  const gradient = getEventGradient(event.colorVar, event.urgent);
  const isCompleted = event.completed === true;

  const formatTime = (hour: number, minute: number) => {
    return `${hour.toString().padStart(2, "0")}:${minute.toString().padStart(2, "0")}`;
  };

  if (typeof document === "undefined") return null;

  return createPortal(
    <motion.div
      ref={modalRef}
      onKeyDown={handleKeyDown}
      role="dialog"
      aria-modal="true"
      aria-labelledby="event-details-title"
      className={cn(
        "fixed inset-0 z-[60] flex items-center justify-center overflow-y-auto overscroll-contain ps-[max(1rem,var(--safe-inline-start))] pe-[max(1rem,var(--safe-inline-end))] pb-[max(1rem,var(--safe-bottom))] pt-[max(1rem,var(--safe-top))]",
        forceDark && "dark",
      )}
      initial={shouldAnimate ? { opacity: 0 } : false}
      animate={{ opacity: 1 }}
      exit={shouldAnimate ? { opacity: 0 } : undefined}
      onClick={onClose}
    >
      {/* Backdrop */}
      <motion.div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        initial={shouldAnimate ? { opacity: 0 } : false}
        animate={{ opacity: 1 }}
        exit={shouldAnimate ? { opacity: 0 } : undefined}
      />

      {/* Modal content */}
      <motion.div
        className="relative max-h-[calc(100dvh-var(--safe-top)-var(--safe-bottom)-2rem)] w-full max-w-xs overflow-x-hidden overflow-y-auto overscroll-contain rounded-3xl"
        initial={shouldAnimate ? { opacity: 0, scale: 0.9, y: 20 } : false}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={shouldAnimate ? { opacity: 0, scale: 0.9, y: 20 } : undefined}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Cosmic background - Theme-aware */}
        <div className="absolute inset-0 bg-gradient-to-br from-amber-50/80 via-sky-50/60 to-indigo-50/40 dark:bg-none" />
        <div
          className="absolute inset-0 hidden dark:block"
          style={{
            background: `linear-gradient(135deg,
              #0f0f23 0%,
              #1a1a3e 50%,
              #2d1b4e 100%)`,
          }}
        />

        <ParticleBackground count={shouldAnimate ? 8 : 0} color="purple" />

        {/* Content */}
        <div className="relative z-10 p-5">
          <div className="text-center mb-4">
            {/* Event icon with glow */}
            <div
              className={cn(
                "w-20 h-20 rounded-2xl mx-auto mb-3 flex items-center justify-center text-4xl relative",
                "bg-gradient-to-br",
                gradient,
                "backdrop-blur-sm border border-white/20",
                shouldAnimate && "[animation:event-glow_2s_ease-in-out_infinite]",
              )}
            >
              <span className={cn(shouldAnimate && "[animation:event-pulse_2s_ease-in-out_infinite]")}>
                {event.emoji}
              </span>

              {isHabitEvent && (
                <span className="absolute -top-1 -end-1 bg-primary rounded-full w-6 h-6 flex items-center justify-center">
                  <Target className="h-4 w-4" aria-hidden="true" />
                </span>
              )}
              {isTaskEvent && (
                <span className="absolute -top-1 -end-1 bg-primary rounded-full w-6 h-6 flex items-center justify-center">
                  <ListChecks className="h-4 w-4" aria-hidden="true" />
                </span>
              )}
            </div>

            <h3
              id="event-details-title"
              className="whitespace-normal [overflow-wrap:anywhere] text-lg font-bold text-slate-800 dark:text-white"
            >
              {event.title}
            </h3>
            <p className="text-sm text-slate-500 dark:text-white/60">
              <bdi dir="ltr">
                {formatTime(event.startHour, event.startMinute)} -{" "}
                {formatTime(event.endHour, event.endMinute)}
              </bdi>
            </p>

            {isCompleted ? (
              <div
                role="status"
                className="mt-3 inline-flex min-h-[48px] items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 text-sm font-semibold text-foreground"
              >
                <CheckCircle2 className="h-4 w-4 shrink-0" aria-hidden="true" />
                <span>{t.scheduleCompletedAt || "Completed at"}</span>
                {event.completedAt !== undefined ? (
                  <time dateTime={new Date(event.completedAt).toISOString()}>
                    {formatLocalizedTime(new Date(event.completedAt), language, {
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </time>
                ) : null}
              </div>
            ) : null}

            {isHabitEvent && (
              <div className="mt-2 px-3 py-1.5 bg-primary/20 rounded-full inline-flex items-center gap-1.5">
                <Target className="h-4 w-4" aria-hidden="true" />
                <span className="text-xs font-medium text-foreground">
                  {t.habitReminder || "Habit Reminder"}
                </span>
              </div>
            )}

            {isTaskEvent && (
              <div className="mt-2 px-3 py-1.5 bg-primary/20 rounded-full inline-flex items-center gap-1.5">
                <ListChecks className="h-4 w-4" aria-hidden="true" />
                <span className="text-xs font-medium text-foreground">
                  {t.autoScheduled || "Auto-scheduled"}
                </span>
              </div>
            )}
          </div>

          {event.note && (
            <div className="mb-4 p-3 bg-secondary backdrop-blur-sm rounded-xl border border-border">
              <p className="whitespace-pre-wrap [overflow-wrap:anywhere] text-sm text-slate-600 dark:text-white/80">
                {event.note}
              </p>
            </div>
          )}

          {isHabitEvent && (
            <div className="mb-4 p-3 bg-green-500/10 rounded-xl border border-green-500/20">
              <p className="break-words hyphens-manual text-xs text-foreground/80">
                {t.habitEventExplanation ||
                  "This event is from your habit. Edit the habit to change it."}
              </p>
            </div>
          )}

          {isTaskEvent && (
            <div className="mb-4 p-3 bg-primary/10 rounded-xl border border-primary/20">
              <p className="break-words hyphens-manual text-xs text-foreground/80">
                {t.taskEventExplanation ||
                  "This block is auto-generated from your tasks. Complete the task to remove it."}
              </p>
            </div>
          )}

          <div className="flex flex-col gap-2 min-[360px]:flex-row">
            <motion.button
              onClick={onClose}
              whileHover={shouldAnimate ? { scale: 1.02 } : undefined}
              whileTap={shouldAnimate ? zenTap.card : undefined}
              className="min-h-[48px] h-auto min-w-0 flex-1 whitespace-normal break-words hyphens-manual rounded-xl border border-border bg-secondary py-3 font-medium text-slate-800 backdrop-blur-sm dark:text-white"
            >
              {t.close || "Close"}
            </motion.button>

            {onDelete &&
              !isHabitEvent &&
              !isAutoGenerated &&
              (showDeleteConfirm ? (
                <motion.button
                  onClick={() => {
                    if (isDeleting) return;
                    setIsDeleting(true);
                    onDelete();
                  }}
                  disabled={isDeleting}
                  whileHover={shouldAnimate ? { scale: 1.02 } : undefined}
                  whileTap={shouldAnimate ? zenTap.card : undefined}
                  className={cn(
                    "min-h-[48px] h-auto min-w-0 flex-1 whitespace-normal break-words hyphens-manual rounded-xl border border-red-500/40 bg-red-500/30 py-3 font-medium text-red-300",
                    isDeleting && "opacity-50",
                  )}
                >
                  {t.confirmDelete || "Confirm?"}
                </motion.button>
              ) : (
                <motion.button
                  onClick={() => setShowDeleteConfirm(true)}
                  whileHover={shouldAnimate ? { scale: 1.02 } : undefined}
                  whileTap={shouldAnimate ? zenTap.card : undefined}
                  className="min-h-[48px] h-auto min-w-0 flex-1 whitespace-normal break-words hyphens-manual rounded-xl border border-red-500/30 bg-red-500/20 py-3 font-medium text-red-400"
                >
                  {t.delete || "Delete"}
                </motion.button>
              ))}
          </div>
        </div>
      </motion.div>
    </motion.div>,
    document.body,
  );
}
