import { motion } from "framer-motion";
import type { KeyboardEvent as ReactKeyboardEvent } from "react";
import { zenTap } from "@/lib/animationUtils";
import { cn } from "@/lib/utils";
import { ScheduleEvent } from "@/types";
import { formatDayShort, getEventColor, HOURS_PER_DAY } from "./constants";
import { formatScheduleTime } from "./scheduleFormatting";

export function ScheduleClock({
  currentHour,
  currentMinute,
  language,
}: {
  currentHour: number;
  currentMinute: number;
  language: string;
}) {
  const dayProgress = ((currentHour * 60 + currentMinute) / (24 * 60)) * 100;
  const circumference = 2 * Math.PI * 42;
  const offset = circumference - (dayProgress / 100) * circumference;
  const machineTime = `${currentHour.toString().padStart(2, "0")}:${currentMinute
    .toString()
    .padStart(2, "0")}`;
  const visibleTime = formatScheduleTime(language, currentHour, currentMinute);

  return (
    <div className="relative h-16 w-16 shrink-0" data-testid="schedule-clock-ring">
      <svg aria-hidden="true" className="h-full w-full -rotate-90" viewBox="0 0 100 100">
        <circle cx="50" cy="50" r="42" fill="none" stroke="hsl(var(--border))" strokeWidth="5" />
        <circle
          cx="50"
          cy="50"
          r="42"
          fill="none"
          stroke="hsl(var(--primary))"
          strokeWidth="5"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
        />
      </svg>

      <time
        className="absolute inset-0 flex min-w-0 max-w-full items-center justify-center whitespace-nowrap text-center text-xs font-semibold leading-none tracking-tight text-foreground [font-variant-numeric:tabular-nums]"
        data-testid="schedule-clock-time"
        dateTime={machineTime}
      >
        {visibleTime}
      </time>
    </div>
  );
}

export function ScheduleDayButton({
  date,
  isSelected,
  isToday,
  hasEvents,
  onClick,
  language,
  accessibleDateLabel,
  eventPresenceLabel,
  tabIndex,
  onKeyDown,
}: {
  date: string;
  isSelected: boolean;
  isToday: boolean;
  hasEvents: boolean;
  onClick: () => void;
  language: string;
  accessibleDateLabel: string;
  eventPresenceLabel: string | undefined;
  tabIndex: number;
  onKeyDown: (event: ReactKeyboardEvent<HTMLButtonElement>) => void;
}) {
  const { day, weekday } = formatDayShort(date, language);
  const accessibleLabel =
    hasEvents && eventPresenceLabel
      ? `${accessibleDateLabel}, ${eventPresenceLabel}`
      : accessibleDateLabel;

  return (
    <motion.button
      type="button"
      onClick={onClick}
      onKeyDown={onKeyDown}
      tabIndex={tabIndex}
      data-schedule-date={date}
      aria-label={accessibleLabel}
      aria-pressed={isSelected}
      aria-current={isToday ? "date" : undefined}
      whileTap={zenTap.button}
      className={cn(
        "relative flex min-h-14 min-w-[60px] flex-shrink-0 snap-start flex-col items-center justify-center rounded-2xl border px-4 py-2.5 text-foreground motion-safe:transition-colors",
        isSelected
          ? "border-primary bg-primary/10 ring-1 ring-primary/40"
          : "border-border bg-secondary hover:bg-secondary/80",
        isToday && !isSelected && "ring-1 ring-primary/40"
      )}
    >
      <bdi dir="auto" className="text-xs font-medium uppercase text-muted-foreground">
        {weekday}
      </bdi>
      <bdi dir="auto" className="text-lg font-bold">
        {day}
      </bdi>

      {hasEvents && (
        <span aria-hidden="true" className="absolute end-2 top-2 h-2 w-2 rounded-full bg-primary" />
      )}
    </motion.button>
  );
}

export function ScheduleEventCard({
  event,
  isCurrent,
  onClick,
  timeRangeLabel,
}: {
  event: ScheduleEvent;
  isCurrent: boolean;
  onClick: () => void;
  timeRangeLabel: string;
}) {
  const eventColor = getEventColor(event.colorVar, event.urgent);
  const isHabitEvent = event.source === "habit";
  const isTaskEvent = event.source === "task";
  const isGoogleEvent = event.source === "google";
  const isAutoGenerated = event.isAutoGenerated;

  const startMinutes = event.startHour * 60 + event.startMinute;
  const endMinutes = event.endHour * 60 + event.endMinute;
  const totalMinutes = HOURS_PER_DAY * 60;
  const left = (startMinutes / totalMinutes) * 100;
  const width = ((endMinutes - startMinutes) / totalMinutes) * 100;

  return (
    <motion.button
      type="button"
      onClick={onClick}
      aria-label={`${event.title}, ${timeRangeLabel}`}
      aria-current={isCurrent ? "time" : undefined}
      whileTap={zenTap.button}
      className={cn(
        "absolute bottom-1.5 top-1.5 flex items-center justify-center gap-1.5 overflow-hidden rounded-lg border border-s-4 border-border bg-card px-2 text-sm font-medium text-foreground motion-safe:transition-colors hover:bg-muted",
        isHabitEvent && "border-dashed",
        isAutoGenerated && "border-dashed",
        isCurrent && "ring-2 ring-primary ring-offset-1 ring-offset-background"
      )}
      style={{
        left: `${left}%`,
        width: `${Math.max(width, 2)}%`,
        borderInlineStartColor: eventColor,
      }}
    >
      {isHabitEvent && (
        <span aria-hidden="true" className="text-xs">
          🎯
        </span>
      )}
      {isTaskEvent && (
        <span aria-hidden="true" className="text-xs">
          📋
        </span>
      )}
      {isGoogleEvent && (
        <span
          aria-hidden="true"
          className="flex h-4 w-4 items-center justify-center rounded-full bg-muted text-[10px] font-semibold"
        >
          G
        </span>
      )}

      <span aria-hidden="true">{event.emoji}</span>
      <bdi dir="auto" className="truncate">
        {event.title}
      </bdi>
    </motion.button>
  );
}

export function CurrentTimeIndicator({ positionPercent }: { positionPercent: number }) {
  return (
    <div
      aria-hidden="true"
      className="absolute bottom-0 top-0 z-20"
      style={{ left: `${positionPercent}%` }}
    >
      <div className="absolute inset-y-0 start-0 w-0.5 bg-primary" />
      <div className="absolute -top-1.5 left-1/2 h-3 w-3 -translate-x-1/2 rounded-full bg-primary" />
      <div className="absolute -bottom-1.5 left-1/2 h-3 w-3 -translate-x-1/2 rounded-full bg-primary" />
    </div>
  );
}
