import { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { getToday, parseLocalDate } from '@/lib/utils';
import { ScheduleEvent } from '@/types';
import { Task } from '@/lib/taskMomentum';
import { safeLocalStorageGet } from '@/lib/safeJson';
import { SK } from '@/lib/storageKeys';
import { fetchCalendarEventsWithCache, isCalendarEnabled, CalendarEvent } from '@/lib/googleCalendar';
import { logger } from '@/lib/logger';
import { useLanguage } from '@/contexts/LanguageContext';
import { shouldAnimate } from '@/lib/animationUtils';
import { isAndroid } from '@/lib/platform';
import {
  EVENT_COLORS,
  getEventColor,
  getExtendedDates,
  HOUR_WIDTH_PX,
  DAY_WIDTH_PX,
} from './constants';
import {
  centeredDomScrollLeft,
  physicalToDomScrollLeft,
} from './timelineScrollCoordinates';

export interface UseScheduleDataReturn {
  currentTime: Date;
  selectedDate: string;
  setSelectedDate: React.Dispatch<React.SetStateAction<string>>;
  tasks: Task[];
  taskEvents: ScheduleEvent[];
  googleEvents: ScheduleEvent[];
  isLoadingGoogle: boolean;
  safeEvents: ScheduleEvent[];
  allDates: string[];
  getDateIndex: (date: string) => number;
  filteredEvents: ScheduleEvent[];
  dateHasEvents: (date: string) => boolean;
  isToday: boolean;
  scrollDaySelectorToDate: (date: string) => void;
  scrollTimelineToDate: (date: string, centerOnCurrentHour?: boolean) => void;
  isScrollingProgrammatically: React.MutableRefObject<boolean>;
  t: ReturnType<typeof useLanguage>['t'];
  language: string;
  isRTL: boolean;
}

export function useScheduleData(
  events: ScheduleEvent[],
  timelineRef: React.RefObject<HTMLDivElement | null>,
  daySelectorRef: React.RefObject<HTMLDivElement | null>,
  initialSelectedDate = getToday(),
): UseScheduleDataReturn {
  const { t, language, isRTL } = useLanguage();
  const [currentTime, setCurrentTime] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState(initialSelectedDate);
  const [tasks, setTasks] = useState<Task[]>([]);
  const isScrollingProgrammatically = useRef(false);

  // Load tasks + time ticker (mount-only)
  useEffect(() => {
    const loadTasks = () => {
      const parsed = safeLocalStorageGet<Task[]>(SK.TASKS, []);
      setTasks(Array.isArray(parsed) ? parsed : []);
    };
    loadTasks();

    const handleStorage = (e: StorageEvent) => {
      if (e.key === SK.TASKS) loadTasks();
    };
    window.addEventListener('storage', handleStorage);

    const handleTasksUpdate = () => loadTasks();
    window.addEventListener('zenflow-tasks-updated', handleTasksUpdate);

    const interval = setInterval(() => setCurrentTime(new Date()), 60000);

    return () => {
      window.removeEventListener('storage', handleStorage);
      window.removeEventListener('zenflow-tasks-updated', handleTasksUpdate);
      clearInterval(interval);
    };
  }, []);

  // Generate auto-schedule events from tasks
  const taskEvents = useMemo((): ScheduleEvent[] => {
    const today = getToday();
    const incompleteTasks = tasks.filter(t => !t.completed);
    if (incompleteTasks.length === 0) return [];

    const generatedEvents: ScheduleEvent[] = [];
    let currentTimestamp = Date.now();

    incompleteTasks.forEach(task => {
      const workDuration = task.estimatedMinutes * 60 * 1000;
      const breakDuration = (task.breakMinutes || 0) * 60 * 1000;

      const workStart = new Date(currentTimestamp);
      const workEnd = new Date(currentTimestamp + workDuration);

      generatedEvents.push({
        id: `task-work-${task.id}`,
        title: task.name,
        startHour: workStart.getHours(),
        startMinute: workStart.getMinutes(),
        endHour: workEnd.getHours(),
        endMinute: workEnd.getMinutes(),
        colorVar: task.urgent ? 'urgent' : 'work',
        color: getEventColor('work', task.urgent),
        urgent: task.urgent,
        emoji: '💼',
        date: today,
        source: 'task',
        taskId: task.id,
        isAutoGenerated: true,
        isEditable: false,
      });

      currentTimestamp += workDuration;

      if (task.breakMinutes && task.breakMinutes > 0) {
        const breakStart = new Date(currentTimestamp);
        const breakEnd = new Date(currentTimestamp + breakDuration);

        generatedEvents.push({
          id: `task-break-${task.id}`,
          title: t.breakTime || 'Break',
          startHour: breakStart.getHours(),
          startMinute: breakStart.getMinutes(),
          endHour: breakEnd.getHours(),
          endMinute: breakEnd.getMinutes(),
          colorVar: 'break',
          color: EVENT_COLORS.break,
          emoji: '☕',
          date: today,
          source: 'task',
          taskId: task.id,
          isAutoGenerated: true,
          isEditable: false,
        });

        currentTimestamp += breakDuration;
      }
    });

    return generatedEvents;
  }, [tasks, t.breakTime]);

  // Google Calendar events
  const [googleEvents, setGoogleEvents] = useState<ScheduleEvent[]>([]);
  const [isLoadingGoogle, setIsLoadingGoogle] = useState(false);

  useEffect(() => {
    if (!isCalendarEnabled()) {
      setGoogleEvents([]);
      return;
    }

    let cancelled = false;

    const loadGoogleEvents = async () => {
      setIsLoadingGoogle(true);
      try {
        const date = parseLocalDate(selectedDate);
        const calEvents = await fetchCalendarEventsWithCache(date);
        if (cancelled) return;

        const mapped: ScheduleEvent[] = calEvents
          .filter((e: CalendarEvent) => !e.isAllDay)
          .map((e: CalendarEvent) => ({
            id: `gcal-${e.id}`,
            title: e.title,
            startHour: e.startTime.getHours(),
            startMinute: e.startTime.getMinutes(),
            endHour: e.endTime.getHours(),
            endMinute: e.endTime.getMinutes(),
            color: e.color || EVENT_COLORS.google,
            colorVar: 'google',
            emoji: '📅',
            date: selectedDate,
            note: e.location || e.description || undefined,
            source: 'google' as const,
            isAutoGenerated: true,
            isEditable: false,
          }));

        setGoogleEvents(mapped);
      } catch (err) {
        logger.error('[ScheduleTimeline] Failed to load Google Calendar events:', err);
      } finally {
        if (!cancelled) setIsLoadingGoogle(false);
      }
    };

    void loadGoogleEvents();
    return () => { cancelled = true; };
  }, [selectedDate]);

  const safeEvents = useMemo(() => {
    const manual = Array.isArray(events) ? events : [];
    return [...manual, ...taskEvents, ...googleEvents];
  }, [events, taskEvents, googleEvents]);

  const allDates = useMemo(() => getExtendedDates(), []);

  const getDateIndex = useCallback((date: string) => {
    return allDates.indexOf(date);
  }, [allDates]);

  const filteredEvents = useMemo(() => {
    return safeEvents.filter(e => e.date === selectedDate);
  }, [safeEvents, selectedDate]);

  const dateHasEvents = useCallback((date: string) => {
    return safeEvents.some(e => e.date === date);
  }, [safeEvents]);

  const isToday = selectedDate === getToday();

  // Scroll helpers
  const scrollDaySelectorToDate = useCallback((date: string) => {
    const daySelector = daySelectorRef.current;
    if (!daySelector) return;
    const index = getDateIndex(date);
    if (index === -1) return;

    const target = daySelector.children.item(index);
    if (!(target instanceof HTMLElement)) return;

    if (isAndroid) {
      daySelector.scrollTo({
        left: centeredDomScrollLeft({
          itemOffsetLeft: target.offsetLeft,
          itemWidth: target.offsetWidth,
          containerWidth: daySelector.clientWidth,
          scrollWidth: daySelector.scrollWidth,
          isRTL,
        }),
        behavior: shouldAnimate() ? "smooth" : "auto",
      });
      return;
    }

    target.scrollIntoView({
      block: "nearest",
      inline: "center",
      behavior: shouldAnimate() ? "smooth" : "auto",
    });
  }, [daySelectorRef, getDateIndex, isRTL]);

  const scrollTimelineToDate = useCallback((date: string, centerOnCurrentHour = false) => {
    if (!timelineRef.current) return;
    const index = getDateIndex(date);
    if (index === -1) return;

    isScrollingProgrammatically.current = true;

    let scrollPosition = index * DAY_WIDTH_PX;

    if (centerOnCurrentHour && date === getToday()) {
      const currentHour = new Date().getHours();
      scrollPosition += currentHour * HOUR_WIDTH_PX;
    }

    const timeline = timelineRef.current;
    scrollPosition -= timeline.clientWidth / 2;
    const maxScroll = timeline.scrollWidth - timeline.clientWidth;
    const domScrollLeft = physicalToDomScrollLeft(scrollPosition, maxScroll, isRTL);

    timeline.scrollTo({
      left: domScrollLeft,
      behavior: shouldAnimate() ? 'smooth' : 'auto',
    });

    setTimeout(() => {
      isScrollingProgrammatically.current = false;
    }, 500);
  }, [timelineRef, getDateIndex, isRTL]);

  // Initial scroll to the requested Planning date. Defaults to today for schedule callers.
  useEffect(() => {
    const initialDate = initialSelectedDate || getToday();
    setSelectedDate(initialDate);
    scrollTimelineToDate(initialDate, initialDate === getToday());
    scrollDaySelectorToDate(initialDate);
  }, [initialSelectedDate, scrollTimelineToDate, scrollDaySelectorToDate]);

  return {
    currentTime,
    selectedDate,
    setSelectedDate,
    tasks,
    taskEvents,
    googleEvents,
    isLoadingGoogle,
    safeEvents,
    allDates,
    getDateIndex,
    filteredEvents,
    dateHasEvents,
    isToday,
    scrollDaySelectorToDate,
    scrollTimelineToDate,
    isScrollingProgrammatically,
    t,
    language,
    isRTL,
  };
}
