/**
 * Journal Prompts Library
 * 200+ directed prompts for mindful writing
 * ADHD-friendly: Short, specific prompts that reduce "blank page anxiety"
 */

import { getToday } from './utils';

export type PromptCategory =
  | 'gratitude'     // Being thankful
  | 'reflection'    // Self-understanding
  | 'emotions'      // Emotional awareness
  | 'goals'         // Aspirations
  | 'relationships' // People in your life
  | 'adhd';         // ADHD-specific support

export interface JournalPrompt {
  id: string;
  category: PromptCategory;
  text: Record<string, string>; // Language code -> prompt text
  starter?: Record<string, string>; // Optional sentence starter
}

// Gratitude prompts (40)
const gratitudePrompts: JournalPrompt[] = [
  { id: 'g1', category: 'gratitude', text: { en: 'What made you smile today?', uk: 'Що змусило тебе посміхнутися сьогодні?', de: 'Was hat dich heute zum Lächeln gebracht?', es: '¿Qué te hizo sonreír hoy?', fr: 'Qu\'est-ce qui t\'a fait sourire aujourd\'hui?', ja: '今日、あなたを笑顔にしたことは何ですか？', ar: 'ما الذي جعلك تبتسم اليوم؟', he: 'מה גרם לך לחייך היום?' }},
  { id: 'g2', category: 'gratitude', text: { en: 'Name three small things you\'re thankful for.', uk: 'Назви три маленькі речі, за які ти вдячний.', de: 'Nenne drei kleine Dinge, für die du dankbar bist.', es: 'Nombra tres cosas pequeñas por las que estás agradecido.', fr: 'Nomme trois petites choses pour lesquelles tu es reconnaissant.', ja: '感謝している小さなことを3つ挙げてみましょう。', ar: 'اذكر ثلاثة أشياء صغيرة تشعر بالامتنان لها.', he: 'ציין שלושה דברים קטנים שאתה אסיר תודה עליהם.' }},
  { id: 'g3', category: 'gratitude', text: { en: 'Who helped you recently? How?', uk: 'Хто тобі нещодавно допоміг? Як?', de: 'Wer hat dir kürzlich geholfen? Wie?', es: '¿Quién te ayudó recientemente? ¿Cómo?', fr: 'Qui t\'a aidé récemment? Comment?', ja: '最近、誰があなたを助けてくれましたか？どのように？', ar: 'من ساعدك مؤخرًا؟ كيف؟', he: 'מי עזר לך לאחרונה? איך?' }},
  { id: 'g4', category: 'gratitude', text: { en: 'What\'s a comfort you often take for granted?', uk: 'Який комфорт ти часто сприймаєш як належне?', de: 'Welchen Komfort nimmst du oft als selbstverständlich hin?', es: '¿Qué comodidad a menudo das por sentada?', fr: 'Quel confort prends-tu souvent pour acquis?', ja: '当たり前だと思いがちな快適さは何ですか？', ar: 'ما الراحة التي غالبًا ما تعتبرها أمرًا مسلّمًا به؟', he: 'איזו נוחות אתה נוטה לקחת כמובנת מאליה?' }},
  { id: 'g5', category: 'gratitude', text: { en: 'What part of your body are you grateful for?', uk: 'За яку частину свого тіла ти вдячний?', de: 'Für welchen Teil deines Körpers bist du dankbar?', es: '¿Por qué parte de tu cuerpo estás agradecido?', fr: 'Pour quelle partie de ton corps es-tu reconnaissant?', ja: '体のどの部分に感謝していますか？', ar: 'ما الجزء من جسدك الذي تشعر بالامتنان له؟', he: 'על איזה חלק בגוף שלך אתה אסיר תודה?' }},
  { id: 'g6', category: 'gratitude', text: { en: 'What technology makes your life easier?', uk: 'Яка технологія полегшує твоє життя?', de: 'Welche Technologie macht dein Leben einfacher?', es: '¿Qué tecnología hace tu vida más fácil?', fr: 'Quelle technologie te facilite la vie?', ja: 'どんなテクノロジーがあなたの生活を楽にしていますか？', ar: 'ما التقنية التي تجعل حياتك أسهل؟', he: 'איזו טכנולוגיה מקלה על החיים שלך?' }},
  { id: 'g7', category: 'gratitude', text: { en: 'What\'s your favorite thing about where you live?', uk: 'Що тобі найбільше подобається в місці, де ти живеш?', de: 'Was magst du am meisten an deinem Wohnort?', es: '¿Qué es lo que más te gusta de donde vives?', fr: 'Qu\'est-ce que tu préfères dans l\'endroit où tu vis?', ja: '住んでいる場所で一番好きなことは何ですか？', ar: 'ما أكثر شيء تحبه في المكان الذي تعيش فيه؟', he: 'מה הדבר האהוב עליך במקום שבו אתה גר?' }},
  { id: 'g8', category: 'gratitude', text: { en: 'What food are you grateful to have access to?', uk: 'За яку їжу ти вдячний?', de: 'Für welches Essen bist du dankbar?', es: '¿Por qué comida estás agradecido?', fr: 'Pour quelle nourriture es-tu reconnaissant?', ja: '食べられることに感謝している食べ物は何ですか？', ar: 'ما الطعام الذي تشعر بالامتنان لتوفره؟', he: 'על איזה אוכל אתה אסיר תודה שיש לך גישה אליו?' }},
  { id: 'g9', category: 'gratitude', text: { en: 'What skill are you glad you have?', uk: 'Якому навику ти радий?', de: 'Über welche Fähigkeit bist du froh?', es: '¿Qué habilidad te alegra tener?', fr: 'De quelle compétence es-tu content?', ja: '持っていてよかったと思うスキルは何ですか？', ar: 'ما المهارة التي تسعد بامتلاكها؟', he: 'על איזה כישרון אתה שמח שיש לך?' }},
  { id: 'g10', category: 'gratitude', text: { en: 'What memory makes you feel warm?', uk: 'Який спогад тебе зігріває?', de: 'Welche Erinnerung wärmt dein Herz?', es: '¿Qué recuerdo te hace sentir cálido?', fr: 'Quel souvenir te réchauffe le cœur?', ja: '心が温かくなる思い出は何ですか？', ar: 'ما الذكرى التي تشعرك بالدفء؟', he: 'איזה זיכרון גורם לך להרגיש חמים?' }},
  { id: 'g11', category: 'gratitude', text: { en: 'What\'s something beautiful you saw today?', uk: 'Що красиве ти бачив сьогодні?', de: 'Was Schönes hast du heute gesehen?', es: '¿Qué cosa hermosa viste hoy?', fr: 'Quelle belle chose as-tu vue aujourd\'hui?', ja: '今日、美しいと思ったものは何ですか？', ar: 'ما الشيء الجميل الذي رأيته اليوم؟', he: 'מה יפה ראית היום?' }},
  { id: 'g12', category: 'gratitude', text: { en: 'What opportunity are you grateful for?', uk: 'За яку можливість ти вдячний?', de: 'Für welche Gelegenheit bist du dankbar?', es: '¿Por qué oportunidad estás agradecido?', fr: 'Pour quelle opportunité es-tu reconnaissant?', ja: 'どんな機会に感謝していますか？', ar: 'ما الفرصة التي تشعر بالامتنان لها؟', he: 'על איזו הזדמנות אתה אסיר תודה?' }},
  { id: 'g13', category: 'gratitude', text: { en: 'What made today better than yesterday?', uk: 'Що зробило сьогоднішній день кращим за вчорашній?', de: 'Was hat heute besser gemacht als gestern?', es: '¿Qué hizo hoy mejor que ayer?', fr: 'Qu\'est-ce qui a rendu aujourd\'hui meilleur qu\'hier?', ja: '昨日より今日がよくなったことは何ですか？', ar: 'ما الذي جعل اليوم أفضل من الأمس؟', he: 'מה הפך את היום לטוב יותר מאתמול?' }},
  { id: 'g14', category: 'gratitude', text: { en: 'Who would you like to thank today?', uk: 'Кого б ти хотів подякувати сьогодні?', de: 'Wem möchtest du heute danken?', es: '¿A quién te gustaría agradecer hoy?', fr: 'Qui voudrais-tu remercier aujourd\'hui?', ja: '今日、感謝を伝えたい人は誰ですか？', ar: 'من تودّ أن تشكر اليوم؟', he: 'למי היית רוצה להודות היום?' }},
  { id: 'g15', category: 'gratitude', text: { en: 'What\'s a lesson you\'re grateful to have learned?', uk: 'За який урок ти вдячний?', de: 'Für welche Lektion bist du dankbar?', es: '¿Por qué lección estás agradecido?', fr: 'Pour quelle leçon es-tu reconnaissant?', ja: '学べてよかったと思う教訓は何ですか？', ar: 'ما الدرس الذي تشعر بالامتنان لتعلّمه؟', he: 'על איזה לקח אתה אסיר תודה שלמדת?' }},
  { id: 'g16', category: 'gratitude', text: { en: 'What in nature inspires gratitude?', uk: 'Що в природі викликає вдячність?', de: 'Was in der Natur inspiriert Dankbarkeit?', es: '¿Qué en la naturaleza inspira gratitud?', fr: 'Qu\'est-ce qui dans la nature inspire la gratitude?', ja: '自然の中で感謝を感じるものは何ですか？', ar: 'ما الذي في الطبيعة يُلهمك الامتنان؟', he: 'מה בטבע מעורר בך תודה?' }},
  { id: 'g17', category: 'gratitude', text: { en: 'What challenge made you stronger?', uk: 'Який виклик зробив тебе сильнішим?', de: 'Welche Herausforderung hat dich stärker gemacht?', es: '¿Qué desafío te hizo más fuerte?', fr: 'Quel défi t\'a rendu plus fort?', ja: 'あなたを強くしてくれた挑戦は何ですか？', ar: 'ما التحدي الذي جعلك أقوى؟', he: 'איזה אתגר עשה אותך חזק יותר?' }},
  { id: 'g18', category: 'gratitude', text: { en: 'What freedom do you appreciate?', uk: 'Яку свободу ти цінуєш?', de: 'Welche Freiheit schätzt du?', es: '¿Qué libertad aprecias?', fr: 'Quelle liberté apprécies-tu?', ja: 'どんな自由に感謝していますか？', ar: 'ما الحرية التي تقدّرها؟', he: 'איזו חירות אתה מעריך?' }},
  { id: 'g19', category: 'gratitude', text: { en: 'What simple pleasure brought you joy?', uk: 'Яке просте задоволення принесло тобі радість?', de: 'Welches einfache Vergnügen hat dir Freude bereitet?', es: '¿Qué placer simple te trajo alegría?', fr: 'Quel plaisir simple t\'a apporté de la joie?', ja: 'どんなささやかな楽しみが喜びをくれましたか？', ar: 'ما المتعة البسيطة التي جلبت لك السعادة؟', he: 'איזו הנאה פשוטה הביאה לך שמחה?' }},
  { id: 'g20', category: 'gratitude', text: { en: 'What are you looking forward to?', uk: 'Чого ти чекаєш з нетерпінням?', de: 'Worauf freust du dich?', es: '¿Qué esperas con ilusión?', fr: 'Qu\'est-ce que tu attends avec impatience?', ja: '楽しみにしていることは何ですか？', ar: 'ما الذي تتطلع إليه؟', he: 'למה אתה מצפה בקוצר רוח?' }},
];

// Reflection prompts (40)
const reflectionPrompts: JournalPrompt[] = [
  { id: 'r1', category: 'reflection', text: { en: 'What did you learn about yourself today?', uk: 'Що ти дізнався про себе сьогодні?', de: 'Was hast du heute über dich gelernt?', es: '¿Qué aprendiste de ti mismo hoy?', fr: 'Qu\'as-tu appris sur toi-même aujourd\'hui?', ja: '今日、自分について何を学びましたか？', ar: 'ماذا تعلّمت عن نفسك اليوم؟', he: 'מה למדת על עצמך היום?' }},
  { id: 'r2', category: 'reflection', text: { en: 'What would you do differently next time?', uk: 'Що б ти зробив інакше наступного разу?', de: 'Was würdest du beim nächsten Mal anders machen?', es: '¿Qué harías diferente la próxima vez?', fr: 'Que ferais-tu différemment la prochaine fois?', ja: '次はどう違うことをしますか？', ar: 'ماذا ستفعل بشكل مختلف في المرة القادمة؟', he: 'מה היית עושה אחרת בפעם הבאה?' }},
  { id: 'r3', category: 'reflection', text: { en: 'What made you proud today?', uk: 'Чим ти пишався сьогодні?', de: 'Worauf warst du heute stolz?', es: '¿De qué estuviste orgulloso hoy?', fr: 'De quoi as-tu été fier aujourd\'hui?', ja: '今日、誇りに思ったことは何ですか？', ar: 'ما الذي جعلك فخورًا اليوم؟', he: 'מה גרם לך להרגיש גאה היום?' }},
  { id: 'r4', category: 'reflection', text: { en: 'What\'s one thing you want to improve?', uk: 'Що ти хочеш покращити?', de: 'Was möchtest du verbessern?', es: '¿Qué quieres mejorar?', fr: 'Que veux-tu améliorer?', ja: '改善したいことは何ですか？', ar: 'ما الشيء الذي تريد تحسينه؟', he: 'מה דבר אחד שאתה רוצה לשפר?' }},
  { id: 'r5', category: 'reflection', text: { en: 'How did you take care of yourself today?', uk: 'Як ти подбав про себе сьогодні?', de: 'Wie hast du heute für dich gesorgt?', es: '¿Cómo cuidaste de ti mismo hoy?', fr: 'Comment as-tu pris soin de toi aujourd\'hui?', ja: '今日、どのように自分を大切にしましたか？', ar: 'كيف اعتنيت بنفسك اليوم؟', he: 'איך דאגת לעצמך היום?' }},
  { id: 'r6', category: 'reflection', text: { en: 'What boundary did you set or need to set?', uk: 'Яку межу ти встановив або хочеш встановити?', de: 'Welche Grenze hast du gesetzt oder musst du setzen?', es: '¿Qué límite estableciste o necesitas establecer?', fr: 'Quelle limite as-tu posée ou dois-tu poser?', ja: 'どんな境界線を設けましたか、または設ける必要がありますか？', ar: 'ما الحدود التي وضعتها أو تحتاج إلى وضعها؟', he: 'איזה גבול הצבת או צריך להציב?' }},
  { id: 'r7', category: 'reflection', text: { en: 'What energized you today?', uk: 'Що надало тобі енергії сьогодні?', de: 'Was hat dir heute Energie gegeben?', es: '¿Qué te dio energía hoy?', fr: 'Qu\'est-ce qui t\'a donné de l\'énergie aujourd\'hui?', ja: '今日、あなたに活力をくれたものは何ですか？', ar: 'ما الذي منحك الطاقة اليوم؟', he: 'מה נתן לך אנרגיה היום?' }},
  { id: 'r8', category: 'reflection', text: { en: 'What drained your energy?', uk: 'Що забрало твою енергію?', de: 'Was hat deine Energie geraubt?', es: '¿Qué te quitó energía?', fr: 'Qu\'est-ce qui a vidé ton énergie?', ja: 'エネルギーを奪ったものは何ですか？', ar: 'ما الذي استنزف طاقتك؟', he: 'מה שאב ממך אנרגיה?' }},
  { id: 'r9', category: 'reflection', text: { en: 'What did you avoid today? Why?', uk: 'Чого ти уникав сьогодні? Чому?', de: 'Was hast du heute vermieden? Warum?', es: '¿Qué evitaste hoy? ¿Por qué?', fr: 'Qu\'as-tu évité aujourd\'hui? Pourquoi?', ja: '今日、避けたことは何ですか？なぜですか？', ar: 'ماذا تجنّبت اليوم؟ لماذا؟', he: 'ממה התחמקת היום? למה?' }},
  { id: 'r10', category: 'reflection', text: { en: 'What surprised you about yourself?', uk: 'Що тебе здивувало в собі?', de: 'Was hat dich an dir selbst überrascht?', es: '¿Qué te sorprendió de ti mismo?', fr: 'Qu\'est-ce qui t\'a surpris chez toi?', ja: '自分自身について意外だったことは何ですか？', ar: 'ما الذي فاجأك في نفسك؟', he: 'מה הפתיע אותך לגבי עצמך?' }},
  { id: 'r11', category: 'reflection', text: { en: 'How did you show kindness today?', uk: 'Як ти проявив доброту сьогодні?', de: 'Wie hast du heute Freundlichkeit gezeigt?', es: '¿Cómo mostraste amabilidad hoy?', fr: 'Comment as-tu fait preuve de gentillesse aujourd\'hui?', ja: '今日、どんな優しさを見せましたか？', ar: 'كيف أظهرت اللطف اليوم؟', he: 'איך הפגנת טוב לב היום?' }},
  { id: 'r12', category: 'reflection', text: { en: 'What pattern do you notice in your week?', uk: 'Яку закономірність ти помічаєш цього тижня?', de: 'Welches Muster bemerkst du in deiner Woche?', es: '¿Qué patrón notas en tu semana?', fr: 'Quel schéma remarques-tu dans ta semaine?', ja: '今週、どんなパターンに気づきましたか？', ar: 'ما النمط الذي تلاحظه في أسبوعك؟', he: 'איזה דפוס אתה מבחין בו השבוע?' }},
  { id: 'r13', category: 'reflection', text: { en: 'What conversation stuck with you?', uk: 'Яка розмова запам\'яталася тобі?', de: 'Welches Gespräch ist dir im Gedächtnis geblieben?', es: '¿Qué conversación te quedó grabada?', fr: 'Quelle conversation t\'est restée en mémoire?', ja: '心に残った会話は何ですか？', ar: 'ما المحادثة التي علقت في ذهنك؟', he: 'איזו שיחה נשארה אצלך בראש?' }},
  { id: 'r14', category: 'reflection', text: { en: 'When did you feel most like yourself?', uk: 'Коли ти відчував себе найбільш собою?', de: 'Wann hast du dich am meisten wie du selbst gefühlt?', es: '¿Cuándo te sentiste más tú mismo?', fr: 'Quand t\'es-tu senti le plus toi-même?', ja: '一番自分らしいと感じたのはいつですか？', ar: 'متى شعرت بأنك أكثر ما تكون على طبيعتك؟', he: 'מתי הרגשת הכי את עצמך?' }},
  { id: 'r15', category: 'reflection', text: { en: 'What would your younger self think of you now?', uk: 'Що б твоє молодше "я" подумало про тебе зараз?', de: 'Was würde dein jüngeres Ich von dir heute denken?', es: '¿Qué pensaría tu yo más joven de ti ahora?', fr: 'Que penserait ton jeune toi de toi maintenant?', ja: '若い頃の自分は、今のあなたをどう思うでしょうか？', ar: 'ماذا كان سيعتقد طفلك الداخلي عنك الآن؟', he: 'מה היה חושב עליך האני הצעיר שלך?' }},
  { id: 'r16', category: 'reflection', text: { en: 'What are you holding onto that you should let go?', uk: 'За що ти тримаєшся, що варто відпустити?', de: 'Woran hältst du fest, das du loslassen solltest?', es: '¿A qué te aferras que deberías soltar?', fr: 'À quoi t\'accroches-tu que tu devrais lâcher?', ja: '手放すべきなのに、しがみついているものは何ですか？', ar: 'ما الذي تتمسك به وينبغي أن تتركه؟', he: 'במה אתה נאחז שכדאי לשחרר?' }},
  { id: 'r17', category: 'reflection', text: { en: 'What made you laugh today?', uk: 'Що змусило тебе сміятися сьогодні?', de: 'Was hat dich heute zum Lachen gebracht?', es: '¿Qué te hizo reír hoy?', fr: 'Qu\'est-ce qui t\'a fait rire aujourd\'hui?', ja: '今日、笑ったことは何ですか？', ar: 'ما الذي أضحكك اليوم؟', he: 'מה גרם לך לצחוק היום?' }},
  { id: 'r18', category: 'reflection', text: { en: 'What do you need more of in your life?', uk: 'Чого тобі потрібно більше в житті?', de: 'Was brauchst du mehr in deinem Leben?', es: '¿Qué necesitas más en tu vida?', fr: 'De quoi as-tu besoin de plus dans ta vie?', ja: '人生にもっと必要なものは何ですか？', ar: 'ما الذي تحتاج إلى المزيد منه في حياتك؟', he: 'ממה אתה צריך יותר בחיים שלך?' }},
  { id: 'r19', category: 'reflection', text: { en: 'What do you need less of?', uk: 'Чого тобі потрібно менше?', de: 'Was brauchst du weniger?', es: '¿Qué necesitas menos?', fr: 'De quoi as-tu besoin de moins?', ja: '減らしたいものは何ですか？', ar: 'ما الذي تحتاج إلى تقليله؟', he: 'ממה אתה צריך פחות?' }},
  { id: 'r20', category: 'reflection', text: { en: 'What small win can you celebrate?', uk: 'Яку маленьку перемогу ти можеш відсвяткувати?', de: 'Welchen kleinen Sieg kannst du feiern?', es: '¿Qué pequeña victoria puedes celebrar?', fr: 'Quelle petite victoire peux-tu célébrer?', ja: 'お祝いできる小さな勝利は何ですか？', ar: 'ما الإنجاز الصغير الذي يمكنك الاحتفال به؟', he: 'איזה ניצחון קטן אתה יכול לחגוג?' }},
];

// Emotions prompts (30)
const emotionsPrompts: JournalPrompt[] = [
  { id: 'e1', category: 'emotions', text: { en: 'What emotion was strongest today?', uk: 'Яка емоція була найсильнішою сьогодні?', de: 'Welche Emotion war heute am stärksten?', es: '¿Qué emoción fue la más fuerte hoy?', fr: 'Quelle émotion a été la plus forte aujourd\'hui?', ja: '今日、一番強く感じた感情は何ですか？', ar: 'ما أقوى شعور راودك اليوم؟', he: 'איזה רגש היה הכי חזק היום?' }},
  { id: 'e2', category: 'emotions', text: { en: 'Where in your body do you feel stress?', uk: 'Де в тілі ти відчуваєш стрес?', de: 'Wo in deinem Körper spürst du Stress?', es: '¿Dónde en tu cuerpo sientes estrés?', fr: 'Où dans ton corps ressens-tu le stress?', ja: '体のどこでストレスを感じますか？', ar: 'أين تشعر بالتوتر في جسدك؟', he: 'איפה בגוף שלך אתה מרגיש לחץ?' }},
  { id: 'e3', category: 'emotions', text: { en: 'What triggered anxiety today?', uk: 'Що викликало тривогу сьогодні?', de: 'Was hat heute Angst ausgelöst?', es: '¿Qué desencadenó ansiedad hoy?', fr: 'Qu\'est-ce qui a déclenché l\'anxiété aujourd\'hui?', ja: '今日、不安を引き起こしたものは何ですか？', ar: 'ما الذي أثار القلق اليوم؟', he: 'מה עורר חרדה היום?' }},
  { id: 'e4', category: 'emotions', text: { en: 'What brought you peace today?', uk: 'Що принесло тобі спокій сьогодні?', de: 'Was hat dir heute Frieden gebracht?', es: '¿Qué te trajo paz hoy?', fr: 'Qu\'est-ce qui t\'a apporté la paix aujourd\'hui?', ja: '今日、心の平穏をもたらしてくれたものは何ですか？', ar: 'ما الذي منحك السكينة اليوم؟', he: 'מה הביא לך שקט היום?' }},
  { id: 'e5', category: 'emotions', text: { en: 'What fear came up today?', uk: 'Який страх з\'явився сьогодні?', de: 'Welche Angst kam heute hoch?', es: '¿Qué miedo surgió hoy?', fr: 'Quelle peur est apparue aujourd\'hui?', ja: '今日、どんな恐れが浮かびましたか？', ar: 'ما الخوف الذي ظهر اليوم؟', he: 'איזה פחד עלה היום?' }},
  { id: 'e6', category: 'emotions', text: { en: 'What made you feel loved?', uk: 'Що змусило тебе відчути себе коханим?', de: 'Was hat dir das Gefühl gegeben, geliebt zu werden?', es: '¿Qué te hizo sentir amado?', fr: 'Qu\'est-ce qui t\'a fait te sentir aimé?', ja: '愛されていると感じたことは何ですか？', ar: 'ما الذي أشعرك بأنك محبوب؟', he: 'מה גרם לך להרגיש אהוב?' }},
  { id: 'e7', category: 'emotions', text: { en: 'What frustration do you need to release?', uk: 'Яке розчарування тобі потрібно відпустити?', de: 'Welche Frustration musst du loslassen?', es: '¿Qué frustración necesitas liberar?', fr: 'Quelle frustration dois-tu libérer?', ja: '手放すべきフラストレーションは何ですか？', ar: 'ما الإحباط الذي تحتاج إلى التخلص منه؟', he: 'איזו תסכול אתה צריך לשחרר?' }},
  { id: 'e8', category: 'emotions', text: { en: 'What emotion are you avoiding?', uk: 'Яку емоцію ти уникаєш?', de: 'Welche Emotion vermeidest du?', es: '¿Qué emoción estás evitando?', fr: 'Quelle émotion évites-tu?', ja: '避けている感情は何ですか？', ar: 'ما الشعور الذي تتجنبه؟', he: 'מאיזה רגש אתה בורח?' }},
  { id: 'e9', category: 'emotions', text: { en: 'How would you describe your mood in one word?', uk: 'Як би ти описав свій настрій одним словом?', de: 'Wie würdest du deine Stimmung mit einem Wort beschreiben?', es: '¿Cómo describirías tu estado de ánimo en una palabra?', fr: 'Comment décrirais-tu ton humeur en un mot?', ja: '今の気分を一言で表すと？', ar: 'كيف تصف مزاجك بكلمة واحدة؟', he: 'איך היית מתאר את מצב הרוח שלך במילה אחת?' }},
  { id: 'e10', category: 'emotions', text: { en: 'What do you need to feel better right now?', uk: 'Що тобі потрібно, щоб почуватися краще?', de: 'Was brauchst du, um dich jetzt besser zu fühlen?', es: '¿Qué necesitas para sentirte mejor ahora?', fr: 'De quoi as-tu besoin pour te sentir mieux maintenant?', ja: '今、気分がよくなるために必要なものは何ですか？', ar: 'ما الذي تحتاجه لتشعر بتحسن الآن؟', he: 'מה אתה צריך כדי להרגיש טוב יותר עכשיו?' }},
  { id: 'e11', category: 'emotions', text: { en: 'What would comfort your inner child?', uk: 'Що б втішило твою внутрішню дитину?', de: 'Was würde dein inneres Kind trösten?', es: '¿Qué consolaría a tu niño interior?', fr: 'Qu\'est-ce qui réconforterait ton enfant intérieur?', ja: '内なる子どもを慰めてあげられることは何ですか？', ar: 'ما الذي يمكن أن يواسي طفلك الداخلي؟', he: 'מה היה מנחם את הילד הפנימי שלך?' }},
  { id: 'e12', category: 'emotions', text: { en: 'What emotion surprised you today?', uk: 'Яка емоція здивувала тебе сьогодні?', de: 'Welche Emotion hat dich heute überrascht?', es: '¿Qué emoción te sorprendió hoy?', fr: 'Quelle émotion t\'a surpris aujourd\'hui?', ja: '今日、意外に感じた感情は何ですか？', ar: 'ما الشعور الذي فاجأك اليوم؟', he: 'איזה רגש הפתיע אותך היום?' }},
  { id: 'e13', category: 'emotions', text: { en: 'What helps you when you feel overwhelmed?', uk: 'Що допомагає тобі, коли ти відчуваєш себе перевантаженим?', de: 'Was hilft dir, wenn du dich überfordert fühlst?', es: '¿Qué te ayuda cuando te sientes abrumado?', fr: 'Qu\'est-ce qui t\'aide quand tu te sens submergé?', ja: '圧倒されたとき、何が助けになりますか？', ar: 'ما الذي يساعدك عندما تشعر بالإرهاق؟', he: 'מה עוזר לך כשאתה מרגיש מוצף?' }},
  { id: 'e14', category: 'emotions', text: { en: 'What made you feel confident?', uk: 'Що змусило тебе відчувати впевненість?', de: 'Was hat dir Selbstvertrauen gegeben?', es: '¿Qué te hizo sentir confiado?', fr: 'Qu\'est-ce qui t\'a donné confiance?', ja: '自信を感じたことは何ですか？', ar: 'ما الذي أشعرك بالثقة؟', he: 'מה גרם לך להרגיש בטוח בעצמך?' }},
  { id: 'e15', category: 'emotions', text: { en: 'What emotion do you want to feel more often?', uk: 'Яку емоцію ти хочеш відчувати частіше?', de: 'Welche Emotion möchtest du öfter fühlen?', es: '¿Qué emoción quieres sentir más a menudo?', fr: 'Quelle émotion veux-tu ressentir plus souvent?', ja: 'もっと頻繁に感じたい感情は何ですか？', ar: 'ما الشعور الذي تريد أن تشعر به أكثر؟', he: 'איזה רגש היית רוצה להרגיש לעיתים קרובות יותר?' }},
];

// Goals prompts (30)
const goalsPrompts: JournalPrompt[] = [
  { id: 'go1', category: 'goals', text: { en: 'What small step did you take toward a goal?', uk: 'Який маленький крок ти зробив до цілі?', de: 'Welchen kleinen Schritt hast du auf ein Ziel hin gemacht?', es: '¿Qué pequeño paso diste hacia una meta?', fr: 'Quel petit pas as-tu fait vers un objectif?', ja: '目標に向けてどんな小さな一歩を踏み出しましたか？', ar: 'ما الخطوة الصغيرة التي اتخذتها نحو هدفك؟', he: 'איזה צעד קטן עשית לקראת מטרה?' }},
  { id: 'go2', category: 'goals', text: { en: 'What dream feels closer today?', uk: 'Яка мрія здається ближчою сьогодні?', de: 'Welcher Traum fühlt sich heute näher an?', es: '¿Qué sueño se siente más cercano hoy?', fr: 'Quel rêve semble plus proche aujourd\'hui?', ja: '今日、近づいたと感じる夢は何ですか？', ar: 'ما الحلم الذي تشعر أنه أصبح أقرب اليوم؟', he: 'איזה חלום מרגיש קרוב יותר היום?' }},
  { id: 'go3', category: 'goals', text: { en: 'What\'s blocking your progress?', uk: 'Що блокує твій прогрес?', de: 'Was blockiert deinen Fortschritt?', es: '¿Qué está bloqueando tu progreso?', fr: 'Qu\'est-ce qui bloque ta progression?', ja: '進歩を妨げているものは何ですか？', ar: 'ما الذي يعيق تقدمك؟', he: 'מה חוסם את ההתקדמות שלך?' }},
  { id: 'go4', category: 'goals', text: { en: 'What habit is helping you most?', uk: 'Яка звичка допомагає тобі найбільше?', de: 'Welche Gewohnheit hilft dir am meisten?', es: '¿Qué hábito te ayuda más?', fr: 'Quelle habitude t\'aide le plus?', ja: '一番役に立っている習慣は何ですか？', ar: 'ما العادة التي تساعدك أكثر؟', he: 'איזו הרגל עוזרת לך הכי הרבה?' }},
  { id: 'go5', category: 'goals', text: { en: 'What would your ideal tomorrow look like?', uk: 'Як би виглядав твій ідеальний завтрашній день?', de: 'Wie würde dein idealer morgiger Tag aussehen?', es: '¿Cómo sería tu mañana ideal?', fr: 'À quoi ressemblerait ton demain idéal?', ja: '理想的な明日はどんな一日ですか？', ar: 'كيف سيبدو غدك المثالي؟', he: 'איך היה נראה המחר האידיאלי שלך?' }},
  { id: 'go6', category: 'goals', text: { en: 'What\'s the next right thing to do?', uk: 'Який наступний правильний крок зробити?', de: 'Was ist das Nächste, was zu tun ist?', es: '¿Cuál es lo siguiente correcto que hacer?', fr: 'Quelle est la prochaine bonne chose à faire?', ja: '次にすべき正しいことは何ですか？', ar: 'ما الشيء الصحيح التالي الذي يجب فعله؟', he: 'מה הדבר הנכון הבא לעשות?' }},
  { id: 'go7', category: 'goals', text: { en: 'What do you want to accomplish this week?', uk: 'Чого ти хочеш досягти цього тижня?', de: 'Was möchtest du diese Woche erreichen?', es: '¿Qué quieres lograr esta semana?', fr: 'Que veux-tu accomplir cette semaine?', ja: '今週、達成したいことは何ですか？', ar: 'ماذا تريد أن تحقق هذا الأسبوع؟', he: 'מה אתה רוצה להשיג השבוע?' }},
  { id: 'go8', category: 'goals', text: { en: 'What would make today a success?', uk: 'Що зробило б сьогоднішній день успішним?', de: 'Was würde heute zu einem Erfolg machen?', es: '¿Qué haría de hoy un éxito?', fr: 'Qu\'est-ce qui ferait d\'aujourd\'hui un succès?', ja: '今日を成功にするためには何が必要ですか？', ar: 'ما الذي سيجعل اليوم ناجحًا؟', he: 'מה היה הופך את היום להצלחה?' }},
  { id: 'go9', category: 'goals', text: { en: 'What fear is holding you back from your goal?', uk: 'Який страх утримує тебе від цілі?', de: 'Welche Angst hält dich von deinem Ziel ab?', es: '¿Qué miedo te impide alcanzar tu meta?', fr: 'Quelle peur te retient d\'atteindre ton objectif?', ja: '目標を阻んでいる恐れは何ですか？', ar: 'ما الخوف الذي يمنعك من تحقيق هدفك؟', he: 'איזה פחד מעכב אותך מהמטרה שלך?' }},
  { id: 'go10', category: 'goals', text: { en: 'What skill do you want to develop?', uk: 'Який навик ти хочеш розвинути?', de: 'Welche Fähigkeit möchtest du entwickeln?', es: '¿Qué habilidad quieres desarrollar?', fr: 'Quelle compétence veux-tu développer?', ja: '身につけたいスキルは何ですか？', ar: 'ما المهارة التي تريد تطويرها؟', he: 'איזה כישרון אתה רוצה לפתח?' }},
  { id: 'go11', category: 'goals', text: { en: 'What would your future self thank you for?', uk: 'За що майбутнє "я" тебе подякує?', de: 'Wofür würde dein zukünftiges Ich dir danken?', es: '¿Por qué te agradecería tu yo futuro?', fr: 'Pour quoi ton futur toi te remercierait-il?', ja: '未来の自分は何に感謝するでしょうか？', ar: 'على ماذا سيشكرك نفسك في المستقبل؟', he: 'על מה העצמי העתידי שלך יודה לך?' }},
  { id: 'go12', category: 'goals', text: { en: 'What\'s one tiny thing you can do right now?', uk: 'Що одне маленьке ти можеш зробити прямо зараз?', de: 'Was ist eine winzige Sache, die du jetzt tun kannst?', es: '¿Qué pequeña cosa puedes hacer ahora mismo?', fr: 'Quelle petite chose peux-tu faire maintenant?', ja: '今すぐできる小さなことは何ですか？', ar: 'ما الشيء الصغير الذي يمكنك فعله الآن؟', he: 'מה דבר קטנטן אחד שאתה יכול לעשות עכשיו?' }},
  { id: 'go13', category: 'goals', text: { en: 'What progress did you make today, even small?', uk: 'Який прогрес ти зробив сьогодні, хай навіть маленький?', de: 'Welchen Fortschritt hast du heute gemacht, auch wenn er klein ist?', es: '¿Qué progreso hiciste hoy, aunque sea pequeño?', fr: 'Quel progrès as-tu fait aujourd\'hui, même petit?', ja: '今日、どんな小さな進歩でもありましたか？', ar: 'ما التقدم الذي أحرزته اليوم، حتى لو كان صغيرًا؟', he: 'איזו התקדמות עשית היום, אפילו קטנה?' }},
  { id: 'go14', category: 'goals', text: { en: 'What\'s working well for you?', uk: 'Що добре працює для тебе?', de: 'Was funktioniert gut für dich?', es: '¿Qué te está funcionando bien?', fr: 'Qu\'est-ce qui fonctionne bien pour toi?', ja: 'うまくいっていることは何ですか？', ar: 'ما الذي يسير على ما يرام بالنسبة لك؟', he: 'מה עובד טוב בשבילך?' }},
  { id: 'go15', category: 'goals', text: { en: 'What\'s not working that you should change?', uk: 'Що не працює, що варто змінити?', de: 'Was funktioniert nicht, das du ändern solltest?', es: '¿Qué no funciona que deberías cambiar?', fr: 'Qu\'est-ce qui ne fonctionne pas que tu devrais changer?', ja: 'うまくいっていなくて変えるべきことは何ですか？', ar: 'ما الذي لا ينجح وينبغي أن تغيّره؟', he: 'מה לא עובד ושכדאי לשנות?' }},
];

// Relationships prompts (30)
const relationshipsPrompts: JournalPrompt[] = [
  { id: 're1', category: 'relationships', text: { en: 'Who made your day better today?', uk: 'Хто зробив твій день кращим сьогодні?', de: 'Wer hat deinen Tag heute besser gemacht?', es: '¿Quién mejoró tu día hoy?', fr: 'Qui a rendu ta journée meilleure aujourd\'hui?', ja: '今日、あなたの一日をよくしてくれた人は誰ですか？', ar: 'من جعل يومك أفضل اليوم؟', he: 'מי עשה את היום שלך טוב יותר?' }},
  { id: 're2', category: 'relationships', text: { en: 'Who do you want to spend more time with?', uk: 'З ким ти хочеш проводити більше часу?', de: 'Mit wem möchtest du mehr Zeit verbringen?', es: '¿Con quién quieres pasar más tiempo?', fr: 'Avec qui veux-tu passer plus de temps?', ja: 'もっと一緒に時間を過ごしたい人は誰ですか？', ar: 'مع من تريد قضاء المزيد من الوقت؟', he: 'עם מי אתה רוצה לבלות יותר זמן?' }},
  { id: 're3', category: 'relationships', text: { en: 'What quality do you admire in someone close?', uk: 'Якою якістю ти захоплюєшся в близькій людині?', de: 'Welche Eigenschaft bewunderst du bei einer nahestehenden Person?', es: '¿Qué cualidad admiras en alguien cercano?', fr: 'Quelle qualité admires-tu chez quelqu\'un de proche?', ja: '身近な人のどんな資質を尊敬していますか？', ar: 'ما الصفة التي تعجبك في شخص قريب منك؟', he: 'איזו תכונה אתה מעריץ במישהו קרוב?' }},
  { id: 're4', category: 'relationships', text: { en: 'Who needs your support right now?', uk: 'Кому зараз потрібна твоя підтримка?', de: 'Wer braucht gerade deine Unterstützung?', es: '¿Quién necesita tu apoyo ahora mismo?', fr: 'Qui a besoin de ton soutien en ce moment?', ja: '今、あなたのサポートが必要な人は誰ですか？', ar: 'من يحتاج إلى دعمك الآن؟', he: 'מי צריך את התמיכה שלך עכשיו?' }},
  { id: 're5', category: 'relationships', text: { en: 'What conversation do you need to have?', uk: 'Яку розмову тобі потрібно провести?', de: 'Welches Gespräch musst du führen?', es: '¿Qué conversación necesitas tener?', fr: 'Quelle conversation dois-tu avoir?', ja: 'しなければならない会話は何ですか？', ar: 'ما المحادثة التي تحتاج إلى إجرائها؟', he: 'איזו שיחה אתה צריך לנהל?' }},
  { id: 're6', category: 'relationships', text: { en: 'How can you show appreciation to someone?', uk: 'Як ти можеш показати вдячність комусь?', de: 'Wie kannst du jemandem Wertschätzung zeigen?', es: '¿Cómo puedes mostrar aprecio a alguien?', fr: 'Comment peux-tu montrer ta reconnaissance à quelqu\'un?', ja: '誰かに感謝の気持ちをどう伝えますか？', ar: 'كيف يمكنك إظهار التقدير لشخص ما؟', he: 'איך אתה יכול להראות הערכה למישהו?' }},
  { id: 're7', category: 'relationships', text: { en: 'What boundary do you need in a relationship?', uk: 'Яка межа тобі потрібна у стосунках?', de: 'Welche Grenze brauchst du in einer Beziehung?', es: '¿Qué límite necesitas en una relación?', fr: 'Quelle limite as-tu besoin dans une relation?', ja: '人間関係で必要な境界線は何ですか？', ar: 'ما الحدود التي تحتاجها في علاقة ما؟', he: 'איזה גבול אתה צריך במערכת יחסים?' }},
  { id: 're8', category: 'relationships', text: { en: 'Who inspires you and why?', uk: 'Хто тебе надихає і чому?', de: 'Wer inspiriert dich und warum?', es: '¿Quién te inspira y por qué?', fr: 'Qui t\'inspire et pourquoi?', ja: '誰に刺激を受けていますか？その理由は？', ar: 'من يُلهمك ولماذا؟', he: 'מי משרה עליך השראה ולמה?' }},
  { id: 're9', category: 'relationships', text: { en: 'What do you miss about someone?', uk: 'Чого тобі не вистачає в комусь?', de: 'Was vermisst du an jemandem?', es: '¿Qué extrañas de alguien?', fr: 'Qu\'est-ce qui te manque chez quelqu\'un?', ja: '誰かについて恋しく思うことは何ですか？', ar: 'ما الذي تفتقده في شخص ما؟', he: 'מה אתה מתגעגע אליו במישהו?' }},
  { id: 're10', category: 'relationships', text: { en: 'How can you be a better friend?', uk: 'Як ти можеш стати кращим другом?', de: 'Wie kannst du ein besserer Freund sein?', es: '¿Cómo puedes ser un mejor amigo?', fr: 'Comment peux-tu être un meilleur ami?', ja: 'もっと良い友達になるにはどうすればいいですか？', ar: 'كيف يمكنك أن تكون صديقًا أفضل؟', he: 'איך אתה יכול להיות חבר טוב יותר?' }},
  { id: 're11', category: 'relationships', text: { en: 'What do you value most in your relationships?', uk: 'Що ти цінуєш найбільше у стосунках?', de: 'Was schätzt du am meisten an deinen Beziehungen?', es: '¿Qué valoras más en tus relaciones?', fr: 'Qu\'est-ce que tu apprécies le plus dans tes relations?', ja: '人間関係で最も大切にしていることは何ですか？', ar: 'ما أكثر ما تقدّره في علاقاتك؟', he: 'מה אתה הכי מעריך במערכות היחסים שלך?' }},
  { id: 're12', category: 'relationships', text: { en: 'Who do you need to forgive?', uk: 'Кого тобі потрібно пробачити?', de: 'Wem musst du vergeben?', es: '¿A quién necesitas perdonar?', fr: 'À qui dois-tu pardonner?', ja: '許すべき人は誰ですか？', ar: 'من تحتاج أن تسامح؟', he: 'למי אתה צריך לסלוח?' }},
  { id: 're13', category: 'relationships', text: { en: 'What quality do you bring to relationships?', uk: 'Яку якість ти привносиш у стосунки?', de: 'Welche Eigenschaft bringst du in Beziehungen ein?', es: '¿Qué cualidad aportas a las relaciones?', fr: 'Quelle qualité apportes-tu dans les relations?', ja: '人間関係にあなたがもたらす良さは何ですか？', ar: 'ما الصفة التي تضيفها إلى علاقاتك؟', he: 'איזו תכונה אתה מביא למערכות יחסים?' }},
  { id: 're14', category: 'relationships', text: { en: 'Who needs to hear "I love you" from you?', uk: 'Кому потрібно почути "Я тебе люблю" від тебе?', de: 'Wer muss "Ich liebe dich" von dir hören?', es: '¿Quién necesita escuchar "Te quiero" de ti?', fr: 'Qui a besoin d\'entendre "Je t\'aime" de ta part?', ja: 'あなたから「愛してるよ」と聞く必要がある人は誰ですか？', ar: 'من يحتاج أن يسمع منك "أحبك"؟', he: 'מי צריך לשמוע ממך "אני אוהב אותך"?' }},
  { id: 're15', category: 'relationships', text: { en: 'What made you feel connected to someone today?', uk: 'Що змусило тебе відчути зв\'язок з кимось сьогодні?', de: 'Was hat dich heute mit jemandem verbunden fühlen lassen?', es: '¿Qué te hizo sentir conectado con alguien hoy?', fr: 'Qu\'est-ce qui t\'a fait te sentir connecté à quelqu\'un aujourd\'hui?', ja: '今日、誰かとのつながりを感じたことは何ですか？', ar: 'ما الذي جعلك تشعر بالارتباط بشخص ما اليوم؟', he: 'מה גרם לך להרגיש מחובר למישהו היום?' }},
];

// ADHD-specific prompts (30)
const adhdPrompts: JournalPrompt[] = [
  { id: 'a1', category: 'adhd', text: { en: 'What helped you focus today?', uk: 'Що допомогло тобі сфокусуватися сьогодні?', de: 'Was hat dir heute geholfen, dich zu konzentrieren?', es: '¿Qué te ayudó a concentrarte hoy?', fr: 'Qu\'est-ce qui t\'a aidé à te concentrer aujourd\'hui?', ja: '今日、集中するのに役立ったことは何ですか？', ar: 'ما الذي ساعدك على التركيز اليوم؟', he: 'מה עזר לך להתרכז היום?' }},
  { id: 'a2', category: 'adhd', text: { en: 'What distracted you the most?', uk: 'Що відволікало тебе найбільше?', de: 'Was hat dich am meisten abgelenkt?', es: '¿Qué te distrajo más?', fr: 'Qu\'est-ce qui t\'a le plus distrait?', ja: '一番気が散ったことは何ですか？', ar: 'ما أكثر شيء شتّت انتباهك؟', he: 'מה הכי הסיח את דעתך?' }},
  { id: 'a3', category: 'adhd', text: { en: 'What time of day were you most productive?', uk: 'В який час дня ти був найбільш продуктивним?', de: 'Zu welcher Tageszeit warst du am produktivsten?', es: '¿A qué hora del día fuiste más productivo?', fr: 'À quelle heure de la journée étais-tu le plus productif?', ja: '一日の中で一番生産性が高かった時間帯は？', ar: 'في أي وقت من اليوم كنت أكثر إنتاجية؟', he: 'באיזו שעה ביום היית הכי פרודוקטיבי?' }},
  { id: 'a4', category: 'adhd', text: { en: 'What task did you keep avoiding?', uk: 'Яке завдання ти продовжував відкладати?', de: 'Welche Aufgabe hast du immer wieder vermieden?', es: '¿Qué tarea seguiste evitando?', fr: 'Quelle tâche as-tu continué à éviter?', ja: 'ずっと先延ばしにしていたタスクは何ですか？', ar: 'ما المهمة التي ظللت تتجنبها؟', he: 'איזו משימה המשכת לדחות?' }},
  { id: 'a5', category: 'adhd', text: { en: 'What helped you start a difficult task?', uk: 'Що допомогло тобі почати складне завдання?', de: 'Was hat dir geholfen, eine schwierige Aufgabe zu beginnen?', es: '¿Qué te ayudó a empezar una tarea difícil?', fr: 'Qu\'est-ce qui t\'a aidé à commencer une tâche difficile?', ja: '難しいタスクを始めるのに何が役立ちましたか？', ar: 'ما الذي ساعدك على البدء بمهمة صعبة؟', he: 'מה עזר לך להתחיל משימה קשה?' }},
  { id: 'a6', category: 'adhd', text: { en: 'How did you manage overwhelm today?', uk: 'Як ти впорався з перевантаженням сьогодні?', de: 'Wie hast du heute Überforderung bewältigt?', es: '¿Cómo manejaste el agobio hoy?', fr: 'Comment as-tu géré le débordement aujourd\'hui?', ja: '今日、圧倒される気持ちにどう対処しましたか？', ar: 'كيف تعاملت مع الشعور بالإرهاق اليوم؟', he: 'איך התמודדת עם עומס היום?' }},
  { id: 'a7', category: 'adhd', text: { en: 'What routine worked well today?', uk: 'Яка рутина добре спрацювала сьогодні?', de: 'Welche Routine hat heute gut funktioniert?', es: '¿Qué rutina funcionó bien hoy?', fr: 'Quelle routine a bien fonctionné aujourd\'hui?', ja: '今日、うまくいったルーティンは何ですか？', ar: 'ما الروتين الذي نجح اليوم؟', he: 'איזה שגרה עבדה טוב היום?' }},
  { id: 'a8', category: 'adhd', text: { en: 'What helped calm your racing thoughts?', uk: 'Що допомогло заспокоїти бігаючі думки?', de: 'Was hat geholfen, deine rasenden Gedanken zu beruhigen?', es: '¿Qué ayudó a calmar tus pensamientos acelerados?', fr: 'Qu\'est-ce qui a aidé à calmer tes pensées qui défilent?', ja: '頭の中をぐるぐる回る思考を落ち着かせたのは何ですか？', ar: 'ما الذي ساعد في تهدئة أفكارك المتسارعة؟', he: 'מה עזר להרגיע את המחשבות המתרוצצות שלך?' }},
  { id: 'a9', category: 'adhd', text: { en: 'What "hack" made life easier today?', uk: 'Який "лайфхак" полегшив життя сьогодні?', de: 'Welcher "Hack" hat das Leben heute einfacher gemacht?', es: '¿Qué "truco" te facilitó la vida hoy?', fr: 'Quelle "astuce" t\'a facilité la vie aujourd\'hui?', ja: '今日、生活を楽にしてくれた「コツ」は何ですか？', ar: 'ما "الحيلة" التي سهّلت حياتك اليوم؟', he: 'איזה "טריק" הקל על החיים שלך היום?' }},
  { id: 'a10', category: 'adhd', text: { en: 'Did you hyperfocus on anything? Was it useful?', uk: 'Ти гіперфокусувався на чомусь? Це було корисно?', de: 'Hast du dich auf etwas hyperfokussiert? War es nützlich?', es: '¿Te hiperconcentraste en algo? ¿Fue útil?', fr: 'As-tu hyperfocalisé sur quelque chose? C\'était utile?', ja: '何かに過集中しましたか？それは役に立ちましたか？', ar: 'هل فرطت في التركيز على شيء ما؟ هل كان مفيدًا؟', he: 'התמקדת יתר על המידה במשהו? זה היה שימושי?' }},
  { id: 'a11', category: 'adhd', text: { en: 'What broke your flow state?', uk: 'Що зламало твій стан потоку?', de: 'Was hat deinen Flow-Zustand unterbrochen?', es: '¿Qué rompió tu estado de flujo?', fr: 'Qu\'est-ce qui a cassé ton état de flow?', ja: 'フロー状態を中断させたものは何ですか？', ar: 'ما الذي قطع حالة التدفق لديك؟', he: 'מה שבר לך את מצב הזרימה?' }},
  { id: 'a12', category: 'adhd', text: { en: 'How was your energy throughout the day?', uk: 'Як була твоя енергія протягом дня?', de: 'Wie war deine Energie im Laufe des Tages?', es: '¿Cómo fue tu energía a lo largo del día?', fr: 'Comment était ton énergie tout au long de la journée?', ja: '一日を通してエネルギーはどうでしたか？', ar: 'كيف كانت طاقتك على مدار اليوم؟', he: 'איך הייתה האנרגיה שלך במהלך היום?' }},
  { id: 'a13', category: 'adhd', text: { en: 'What reminder or alarm was most helpful?', uk: 'Яке нагадування було найкориснішим?', de: 'Welche Erinnerung war am hilfreichsten?', es: '¿Qué recordatorio fue más útil?', fr: 'Quel rappel a été le plus utile?', ja: '一番役に立ったリマインダーやアラームは何ですか？', ar: 'ما التذكير أو المنبه الذي كان أكثر فائدة؟', he: 'איזו תזכורת או התראה הייתה הכי מועילה?' }},
  { id: 'a14', category: 'adhd', text: { en: 'Did you take any breaks? How did they help?', uk: 'Ти робив перерви? Як вони допомогли?', de: 'Hast du Pausen gemacht? Wie haben sie geholfen?', es: '¿Tomaste descansos? ¿Cómo ayudaron?', fr: 'As-tu pris des pauses? Comment ont-elles aidé?', ja: '休憩を取りましたか？どう役立ちましたか？', ar: 'هل أخذت أي استراحات؟ كيف ساعدتك؟', he: 'לקחת הפסקות? איך הן עזרו?' }},
  { id: 'a15', category: 'adhd', text: { en: 'What "boring" task did you make fun?', uk: 'Яке "нудне" завдання ти зробив веселим?', de: 'Welche "langweilige" Aufgabe hast du unterhaltsam gemacht?', es: '¿Qué tarea "aburrida" hiciste divertida?', fr: 'Quelle tâche "ennuyeuse" as-tu rendue amusante?', ja: '「退屈な」タスクをどうやって楽しくしましたか？', ar: 'ما المهمة "المملة" التي حوّلتها إلى ممتعة؟', he: 'איזו משימה "משעממת" הפכת למהנה?' }},
  { id: 'a16', category: 'adhd', text: { en: 'What do you need to forgive yourself for?', uk: 'За що тобі потрібно пробачити себе?', de: 'Wofür musst du dir selbst vergeben?', es: '¿Por qué necesitas perdonarte?', fr: 'Pour quoi dois-tu te pardonner?', ja: '自分を許すべきことは何ですか？', ar: 'على ماذا تحتاج أن تسامح نفسك؟', he: 'על מה אתה צריך לסלוח לעצמך?' }},
  { id: 'a17', category: 'adhd', text: { en: 'What ADHD superpower did you use today?', uk: 'Яку СДУГ-суперсилу ти використав сьогодні?', de: 'Welche ADHS-Superkraft hast du heute genutzt?', es: '¿Qué superpoder TDAH usaste hoy?', fr: 'Quel superpouvoir TDAH as-tu utilisé aujourd\'hui?', ja: '今日、ADHDの超能力をどう活かしましたか？', ar: 'ما القوة الخارقة لفرط الحركة التي استخدمتها اليوم؟', he: 'איזו כוח-על של ADHD השתמשת בו היום?' }},
  { id: 'a18', category: 'adhd', text: { en: 'What new idea excited you today?', uk: 'Яка нова ідея схвилювала тебе сьогодні?', de: 'Welche neue Idee hat dich heute begeistert?', es: '¿Qué nueva idea te emocionó hoy?', fr: 'Quelle nouvelle idée t\'a enthousiasmé aujourd\'hui?', ja: '今日、わくわくした新しいアイデアは何ですか？', ar: 'ما الفكرة الجديدة التي أثارت حماسك اليوم؟', he: 'איזה רעיון חדש ריגש אותך היום?' }},
  { id: 'a19', category: 'adhd', text: { en: 'How did you handle time blindness today?', uk: 'Як ти впорався з "часовою сліпотою" сьогодні?', de: 'Wie bist du heute mit Zeitblindheit umgegangen?', es: '¿Cómo manejaste la ceguera temporal hoy?', fr: 'Comment as-tu géré la cécité temporelle aujourd\'hui?', ja: '今日、時間感覚の弱さにどう対処しましたか？', ar: 'كيف تعاملت مع عمى الوقت اليوم؟', he: 'איך התמודדת עם עיוורון זמן היום?' }},
  { id: 'a20', category: 'adhd', text: { en: 'What transition was hardest today?', uk: 'Який перехід був найскладнішим сьогодні?', de: 'Welcher Übergang war heute am schwierigsten?', es: '¿Qué transición fue la más difícil hoy?', fr: 'Quelle transition a été la plus difficile aujourd\'hui?', ja: '今日、一番大変だった切り替えは何ですか？', ar: 'ما أصعب انتقال واجهته اليوم؟', he: 'איזה מעבר היה הכי קשה היום?' }},
];

// All prompts combined
export const ALL_PROMPTS: JournalPrompt[] = [
  ...gratitudePrompts,
  ...reflectionPrompts,
  ...emotionsPrompts,
  ...goalsPrompts,
  ...relationshipsPrompts,
  ...adhdPrompts,
];

// Category labels
export const CATEGORY_LABELS: Record<PromptCategory, Record<string, string>> = {
  gratitude: { en: 'Gratitude', uk: 'Вдячність', de: 'Dankbarkeit', es: 'Gratitud', fr: 'Gratitude', ja: '感謝', ar: 'امتنان', he: 'הכרת תודה' },
  reflection: { en: 'Reflection', uk: 'Рефлексія', de: 'Reflexion', es: 'Reflexión', fr: 'Réflexion', ja: '振り返り', ar: 'تأمل', he: 'רפלקציה' },
  emotions: { en: 'Emotions', uk: 'Емоції', de: 'Emotionen', es: 'Emociones', fr: 'Émotions', ja: '感情', ar: 'مشاعر', he: 'רגשות' },
  goals: { en: 'Goals', uk: 'Цілі', de: 'Ziele', es: 'Metas', fr: 'Objectifs', ja: '目標', ar: 'أهداف', he: 'מטרות' },
  relationships: { en: 'Relationships', uk: 'Стосунки', de: 'Beziehungen', es: 'Relaciones', fr: 'Relations', ja: '人間関係', ar: 'علاقات', he: 'מערכות יחסים' },
  adhd: { en: 'ADHD', uk: 'СДУГ', de: 'ADHS', es: 'TDAH', fr: 'TDAH', ja: 'ADHD', ar: 'فرط الحركة', he: 'ADHD' },
};

/** Get prompts filtered by category */
export function getPromptsByCategory(category: PromptCategory): JournalPrompt[] {
  return ALL_PROMPTS.filter(p => p.category === category);
}

/** Get a random prompt */
export function getRandomPrompt(category?: PromptCategory): JournalPrompt {
  const prompts = category ? getPromptsByCategory(category) : ALL_PROMPTS;
  return prompts[Math.floor(Math.random() * prompts.length)];
}

/** Get daily prompt based on date (consistent for the day) */
export function getDailyPrompt(date: string = getToday()): JournalPrompt {
  // Simple hash from date string
  let hash = 0;
  for (let i = 0; i < date.length; i++) {
    const char = date.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  const index = Math.abs(hash) % ALL_PROMPTS.length;
  return ALL_PROMPTS[index];
}

/** Get prompt text in specified language */
export function getPromptText(prompt: JournalPrompt, lang: string): string {
  return prompt.text[lang] || prompt.text.en;
}
