import { afterAll, beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  rpc: vi.fn(),
  enqueue: vi.fn(),
  processQueue: vi.fn(),
  getState: vi.fn(),
  validateSyncOwner: vi.fn(),
  triggerDataRefresh: vi.fn(),
  getPersistentDeviceId: vi.fn(),
  broadcastChange: vi.fn(),
}));

vi.mock("@/lib/supabaseClient", () => ({
  supabase: { rpc: mocks.rpc },
}));

vi.mock("@/lib/offlineQueue", () => ({
  offlineQueue: {
    enqueue: mocks.enqueue,
    processQueue: mocks.processQueue,
    getState: mocks.getState,
  },
}));

vi.mock("@/storage/sync/syncOwner", () => ({
  validateSyncOwner: mocks.validateSyncOwner,
}));

vi.mock("@/hooks/useIndexedDB", () => ({
  triggerDataRefresh: mocks.triggerDataRefresh,
}));

vi.mock("@/storage/eventSync", () => ({
  getPersistentDeviceId: mocks.getPersistentDeviceId,
}));

vi.mock("@/lib/syncBroadcast", () => ({
  broadcastChange: mocks.broadcastChange,
}));

vi.mock("@/lib/logger", () => ({
  logger: { log: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));

import { db } from "@/storage/db";
import {
  AUTOMATION_PREFERENCE_SETTING_KEY,
  type AutomationPreference,
} from "../types";
import { recordRevisionId } from "../automationRepository";
import { hashAutomationValue } from "../revisionCrypto";
import {
  createDisabledAutomationPreference,
  enableAutomationPreference,
  flushAutomationPreferenceRevocation,
  mergeAutomationPreference,
  readAutomationPreference,
  revokeAutomationPreference,
} from "../automationPreferences";

const OWNER_ID = "11111111-1111-4111-8111-111111111111";
const CONSENT_EPOCH = "33333333-3333-4333-8333-333333333333";

function enabledPreference(serverRevision = 5): AutomationPreference {
  return {
    schemaVersion: 1,
    enabled: true,
    serverRevision,
    consentEpoch: CONSENT_EPOCH,
    consentedAt: 100,
    revokedAt: null,
    revocationPending: false,
    enabledRuleIds: ["mood.note-to-journal.v1"],
    focusHabitId: null,
    focusMinimumMinutes: 25,
    planningHabitMappings: {},
    updatedAt: 100,
  };
}

function disabledPreference(
  serverRevision = 4,
  overrides: Partial<AutomationPreference> = {},
): AutomationPreference {
  return {
    ...createDisabledAutomationPreference(90),
    serverRevision,
    ...overrides,
  };
}

describe("automation preferences", () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    Object.defineProperty(navigator, "onLine", {
      configurable: true,
      value: true,
    });
    mocks.validateSyncOwner.mockResolvedValue(OWNER_ID);
    mocks.enqueue.mockResolvedValue(undefined);
    mocks.processQueue.mockResolvedValue(undefined);
    mocks.triggerDataRefresh.mockResolvedValue(undefined);
    mocks.getPersistentDeviceId.mockResolvedValue("android-device-1");
    mocks.getState.mockReturnValue({ actions: [], isProcessing: false, lastProcessedAt: null });
    await db.open();
    await db.settings.clear();
  });

  afterAll(() => {
    db.close();
  });

  it("defaults to a local fail-closed preference without inventing server consent", async () => {
    await expect(readAutomationPreference()).resolves.toEqual(
      expect.objectContaining({
        enabled: false,
        serverRevision: 0,
        consentEpoch: null,
        revocationPending: false,
      }),
    );
    expect(mocks.rpc).not.toHaveBeenCalled();
  });

  it("requires an online, current-owner CAS response before enabling", async () => {
    await db.settings.put({
      key: AUTOMATION_PREFERENCE_SETTING_KEY,
      value: disabledPreference(4),
    });
    mocks.rpc.mockResolvedValue({ data: enabledPreference(5), error: null });

    const result = await enableAutomationPreference(
      {
        enabledRuleIds: ["mood.note-to-journal.v1"],
        focusHabitId: null,
        focusMinimumMinutes: 25,
        planningHabitMappings: {},
      },
      OWNER_ID,
    );

    expect(mocks.rpc).toHaveBeenCalledWith("set_automation_preference", {
      p_expected_server_revision: 4,
      p_enabled_rule_ids: ["mood.note-to-journal.v1"],
      p_focus_habit_id: null,
      p_focus_minimum_minutes: 25,
      p_planning_habit_mappings: {},
    });
    expect(result).toEqual(enabledPreference(5));
    await expect(db.settings.get(AUTOMATION_PREFERENCE_SETTING_KEY)).resolves.toMatchObject({
      value: enabledPreference(5),
    });
  });

  it("atomically stores an explicit planning block and its authoritative setting revision", async () => {
    const planningBlock = {
      id: "habit-h1-2026-08-09-0",
      title: "Read",
      startHour: 9,
      startMinute: 0,
      endHour: 9,
      endMinute: 30,
      color: "#334455",
      date: "2026-08-09",
      source: "habit" as const,
      habitId: "h1",
      isAutoGenerated: true,
      isEditable: false,
      completed: false,
    };
    const stateHash = await hashAutomationValue([planningBlock]);
    const preference: AutomationPreference = {
      ...enabledPreference(5),
      enabledRuleIds: ["habit.to-planning.v1"],
      planningHabitMappings: { h1: planningBlock.id },
    };
    await db.settings.put({
      key: AUTOMATION_PREFERENCE_SETTING_KEY,
      value: disabledPreference(4),
    });
    mocks.rpc.mockResolvedValue({
      data: {
        preference,
        scheduleEvents: [planningBlock],
        scheduleRevision: {
          recordExists: true,
          revisionToken: "44444444-4444-4444-8444-444444444444",
          stateHash,
          mutationGeneration: 1,
          transactionId: null,
          updatedAt: 101,
        },
        eventSeq: 42,
      },
      error: null,
    });

    await expect(
      enableAutomationPreference(
        {
          enabledRuleIds: ["habit.to-planning.v1"],
          focusHabitId: null,
          focusMinimumMinutes: 25,
          planningHabitMappings: { h1: planningBlock.id },
          planningBlocks: [planningBlock],
        },
        OWNER_ID,
      ),
    ).resolves.toEqual(preference);

    expect(mocks.rpc).toHaveBeenCalledWith("set_automation_preference_with_planning", {
      p_expected_server_revision: 4,
      p_enabled_rule_ids: ["habit.to-planning.v1"],
      p_focus_habit_id: null,
      p_focus_minimum_minutes: 25,
      p_planning_habit_mappings: { h1: planningBlock.id },
      p_planning_blocks: [planningBlock],
      p_device_id: "android-device-1",
    });
    await expect(db.settings.get("zenflow-schedule-events")).resolves.toEqual({
      key: "zenflow-schedule-events",
      value: [planningBlock],
    });
    await expect(
      db.automationTransactions.get(recordRevisionId("setting", "zenflow-schedule-events")),
    ).resolves.toMatchObject({
      kind: "record_revision",
      ownerUserId: OWNER_ID,
      entityType: "setting",
      entityId: "zenflow-schedule-events",
      revisionToken: "44444444-4444-4444-8444-444444444444",
      stateHash,
      mutationGeneration: 1,
      transactionId: null,
    });
    expect(mocks.triggerDataRefresh).toHaveBeenCalledTimes(1);
    expect(mocks.broadcastChange).toHaveBeenCalledWith("settings", 42);
  });

  it("never queues an offline enable with a stale expected revision", async () => {
    Object.defineProperty(navigator, "onLine", {
      configurable: true,
      value: false,
    });

    await expect(
      enableAutomationPreference(
        {
          enabledRuleIds: ["mood.note-to-journal.v1"],
          focusHabitId: null,
          focusMinimumMinutes: 25,
          planningHabitMappings: {},
        },
        OWNER_ID,
      ),
    ).rejects.toMatchObject({ code: "AUTOMATION_ENABLE_REQUIRES_ONLINE" });

    expect(mocks.enqueue).not.toHaveBeenCalled();
    expect(mocks.rpc).not.toHaveBeenCalled();
  });

  it("persists a fail-closed revocation before queuing its critical offline retry", async () => {
    await db.settings.put({
      key: AUTOMATION_PREFERENCE_SETTING_KEY,
      value: enabledPreference(5),
    });
    Object.defineProperty(navigator, "onLine", {
      configurable: true,
      value: false,
    });

    let storedBeforeQueue: unknown;
    mocks.enqueue.mockImplementationOnce(async () => {
      storedBeforeQueue = (await db.settings.get(AUTOMATION_PREFERENCE_SETTING_KEY))?.value;
    });

    const result = await revokeAutomationPreference(OWNER_ID, 120);

    expect(storedBeforeQueue).toMatchObject({
      enabled: false,
      consentEpoch: null,
      revokedAt: 120,
      revocationPending: true,
      serverRevision: 5,
    });
    expect(mocks.enqueue).toHaveBeenCalledWith(
      "REVOKE_AUTOMATION_PREFERENCE",
      AUTOMATION_PREFERENCE_SETTING_KEY,
      { schemaVersion: 1, requestedAt: 120 },
      { expectedOwnerUserId: OWNER_ID, priority: "critical" },
    );
    expect(result.status).toBe("pending");
    expect(mocks.rpc).not.toHaveBeenCalled();
  });

  it("flushes a durable revoke through the dedicated RPC and stores only its disabled response", async () => {
    await db.settings.put({
      key: AUTOMATION_PREFERENCE_SETTING_KEY,
      value: disabledPreference(5, {
        consentedAt: 100,
        revokedAt: 120,
        revocationPending: true,
        updatedAt: 120,
      }),
    });
    const accepted = disabledPreference(6, {
      consentedAt: 100,
      revokedAt: 121,
      updatedAt: 121,
    });
    mocks.rpc.mockResolvedValue({ data: accepted, error: null });

    const result = await flushAutomationPreferenceRevocation(
      { schemaVersion: 1, requestedAt: 120 },
      OWNER_ID,
    );

    expect(mocks.rpc).toHaveBeenCalledWith("revoke_automation_preference");
    expect(result).toEqual(accepted);
    await expect(db.settings.get(AUTOMATION_PREFERENCE_SETTING_KEY)).resolves.toMatchObject({
      value: accepted,
    });
  });

  it("keeps a pending local disable ahead of a newer enabled snapshot", () => {
    const pending = disabledPreference(5, {
      consentedAt: 100,
      revokedAt: 120,
      revocationPending: true,
      updatedAt: 120,
    });

    expect(mergeAutomationPreference(pending, enabledPreference(6))).toEqual(pending);
    expect(
      mergeAutomationPreference(
        disabledPreference(5),
        disabledPreference(6, { revokedAt: 121, updatedAt: 121 }),
      ),
    ).toEqual(disabledPreference(6, { revokedAt: 121, updatedAt: 121 }));
  });

  it("rejects malformed or unexpectedly enabled revoke responses without overwriting local state", async () => {
    const pending = disabledPreference(5, {
      consentedAt: 100,
      revokedAt: 120,
      revocationPending: true,
      updatedAt: 120,
    });
    await db.settings.put({ key: AUTOMATION_PREFERENCE_SETTING_KEY, value: pending });
    mocks.rpc.mockResolvedValue({ data: enabledPreference(6), error: null });

    await expect(
      flushAutomationPreferenceRevocation(
        { schemaVersion: 1, requestedAt: 120 },
        OWNER_ID,
      ),
    ).rejects.toMatchObject({ code: "AUTOMATION_PREFERENCE_INVALID_RESPONSE" });

    await expect(db.settings.get(AUTOMATION_PREFERENCE_SETTING_KEY)).resolves.toMatchObject({
      value: pending,
    });
  });
});
