import { useEffect, useMemo, useRef, useState } from "react";
import { createRoot, type Root } from "react-dom/client";
import { CalendarCheck2, Link2 } from "lucide-react";

import "@/index.css";
import { GlobalScheduleBar } from "@/components/GlobalScheduleBar";
import { EventDetailsModal } from "@/components/schedule/EventDetailsModal";
import { TimelineDayColumn } from "@/components/schedule/TimelineDayColumn";
import { DAY_WIDTH_PX, HOUR_WIDTH_PX } from "@/components/schedule/constants";
import { LanguageProvider, useLanguage } from "@/contexts/LanguageContext";
import { HabitPlanningMappingsField } from "@/features/automation/HabitPlanningMappingsField";
import {
  PanelFrame,
  SettingsInlineButton,
  SettingsInset,
  ToggleRow,
} from "@/pages/nav-v2/settings/components/V2SettingsControlPrimitives";
import type { Language } from "@/i18n/translations";
import type { Habit, ScheduleEvent } from "@/types";

const params = new URLSearchParams(window.location.search);
const requestedLanguage = (params.get("lang") || "en") as Language;
const requestedTheme = params.get("theme") === "dark" ? "dark" : "light";

document.documentElement.classList.toggle("dark", requestedTheme === "dark");
document.documentElement.dataset.theme = requestedTheme === "dark" ? "ink" : "paper";
document.documentElement.style.colorScheme = requestedTheme;

const HABIT_NAME: Partial<Record<Language, string>> = {
  ar: "قراءة هادئة",
  he: "קריאה שקטה",
  de: "Ruhig lesen",
  es: "Lectura tranquila",
  fr: "Lecture calme",
  ja: "静かな読書",
  uk: "Спокійне читання",
};

function VisualFixture() {
  const { language, setLanguage, t } = useLanguage();
  const [detailsOpen, setDetailsOpen] = useState(false);
  const timelineViewportRef = useRef<HTMLDivElement>(null);
  const habitName = HABIT_NAME[requestedLanguage] || "Quiet reading";

  useEffect(() => {
    if (language !== requestedLanguage) setLanguage(requestedLanguage);
  }, [language, setLanguage]);

  useEffect(() => {
    if (language === requestedLanguage && timelineViewportRef.current) {
      timelineViewportRef.current.scrollLeft = 8 * HOUR_WIDTH_PX - 24;
    }
  }, [language]);

  const habit = useMemo<Habit>(
    () => ({
      id: "11111111-1111-4111-8111-111111111111",
      name: habitName,
      icon: "book-open",
      color: 7,
      position: 0,
      createdAt: 1,
      habitType: "boolean",
      frequency: { numerator: 1, denominator: 1 },
      question: "",
      description: "",
      isArchived: false,
      targetValue: 1,
      targetType: "atLeast",
      unit: "",
      entries: {},
      reminders: [{ enabled: true, time: "08:30", days: [0, 1, 2, 3, 4, 5, 6] }],
    }),
    [habitName],
  );

  const candidate = useMemo<ScheduleEvent>(
    () => ({
      id: "habit-11111111-1111-4111-8111-111111111111-2026-08-09-08-30",
      title: habitName,
      startHour: 8,
      startMinute: 30,
      endHour: 9,
      endMinute: 0,
      color: "hsl(var(--primary))",
      colorVar: "habit",
      emoji: "📖",
      date: "2026-08-09",
      source: "habit",
      habitId: habit.id,
      isAutoGenerated: true,
      isEditable: false,
      completed: false,
    }),
    [habit.id, habitName],
  );

  const completedEvent = useMemo<ScheduleEvent>(
    () => ({
      ...candidate,
      completed: true,
      completedAt: new Date(2026, 7, 9, 8, 52).getTime(),
    }),
    [candidate],
  );

  if (language !== requestedLanguage) {
    return (
      <main className="min-h-[100dvh] bg-background p-6 text-foreground">
        <p role="status">Loading locale…</p>
      </main>
    );
  }

  return (
    <main
      className="min-h-[100dvh] overflow-x-hidden bg-background px-[max(1rem,var(--safe-inline-start))] pb-[max(2rem,var(--safe-bottom))] pt-[max(1rem,var(--safe-top))] text-foreground"
      data-testid="t150-visual-fixture"
      data-language={language}
      data-theme={requestedTheme}
    >
      <div className="mx-auto w-full max-w-md space-y-5">
        <section data-testid="t150-settings-surface" aria-label={t.connectedRecordsTitle}>
          <PanelFrame
            icon={Link2}
            title={t.connectedRecordsTitle}
            description={t.connectedRecordsDescription}
          >
            <ToggleRow
              icon={CalendarCheck2}
              title={t.connectedRecordsRuleHabitPlanning}
              description={t.connectedRecordsRuleHabitPlanningHint}
              checked
              onCheckedChange={() => undefined}
              surfaceWeight="quiet"
            />
            <SettingsInset>
              <HabitPlanningMappingsField
                habits={[habit]}
                candidates={[candidate]}
                mappings={{ [habit.id]: candidate.id }}
                onChange={() => undefined}
              />
              <SettingsInlineButton icon={CalendarCheck2} variant="primary">
                {t.connectedRecordsSaveRules}
              </SettingsInlineButton>
            </SettingsInset>
          </PanelFrame>
        </section>

        <section
          className="space-y-3 rounded-[8px] border border-border/50 bg-card/60 p-3"
          data-testid="t150-completed-surface"
          aria-label={t.viewSchedule}
        >
          <GlobalScheduleBar events={[completedEvent]} />
          <div
            ref={timelineViewportRef}
            className="h-28 overflow-x-auto overflow-y-hidden rounded-2xl border border-border/50 bg-secondary/55"
          >
            <div className="relative h-28" style={{ width: `${DAY_WIDTH_PX}px` }}>
              <TimelineDayColumn
                date={completedEvent.date}
                dayOffset={0}
                dayEvents={[completedEvent]}
                isDayToday={false}
                isDaySelected
                currentHour={17}
                currentTimePositionPercent={0}
                language={language}
                t={t}
                onEventClick={() => setDetailsOpen(true)}
                isEventCurrent={() => true}
              />
            </div>
          </div>
          <SettingsInlineButton
            icon={CalendarCheck2}
            onClick={() => setDetailsOpen(true)}
          >
            {t.viewDetails}
          </SettingsInlineButton>
        </section>
      </div>

      {detailsOpen ? (
        <EventDetailsModal event={completedEvent} onClose={() => setDetailsOpen(false)} />
      ) : null}
    </main>
  );
}

const fixtureWindow = window as Window & { __zenflowT150Root?: Root };
const fixtureRoot = fixtureWindow.__zenflowT150Root ?? createRoot(document.getElementById("root")!);
fixtureWindow.__zenflowT150Root = fixtureRoot;

fixtureRoot.render(
  <LanguageProvider>
    <VisualFixture />
  </LanguageProvider>,
);
