import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  ACCOUNT_OWNED_SECRET_NAMES,
  formatGeneratedSecretsEnv,
  formatRedactedGeneratedSecrets,
  generateProjectSecrets,
  validateGeneratedSecrets,
} from "../src/secret-bootstrap";

const root = resolve(import.meta.dirname, "../../..");
const defaultTarget = resolve(root, ".env.telegram-control.local");
const args = process.argv.slice(2);
const writeLocal = args.includes("--write-local");
const force = args.includes("--force");
const secrets = generateProjectSecrets();
const validationErrors = validateGeneratedSecrets(secrets);

function writeGeneratedSecretsToDefaultLocalFile(content: string): void {
  writeFileSync(defaultTarget, content, { encoding: "utf8", flag: "w" });
}

console.log(`Telegram generated-secret bootstrap: ${validationErrors.length === 0 ? "PASS" : "FAIL"}`);

if (validationErrors.length > 0) {
  for (const error of validationErrors) {
    console.error(`FAIL ${error}`);
  }
  process.exit(1);
}

for (const line of formatRedactedGeneratedSecrets(secrets)) {
  console.log(`PASS ${line}`);
}

console.log("");
console.log("Account-owned secrets not generated by this helper:");
for (const name of ACCOUNT_OWNED_SECRET_NAMES) {
  console.log(`UNVERIFIED ${name} - requires an official account/key source`);
}

if (!writeLocal) {
  console.log("");
  console.log("Dry run only. Re-run with --write-local to write the generated project secrets to an ignored local env file.");
  console.log(`Target: ${defaultTarget}`);
  process.exit(0);
}

if (existsSync(defaultTarget) && !force) {
  console.error(`Refusing to overwrite existing file without --force: ${defaultTarget}`);
  process.exit(1);
}

writeGeneratedSecretsToDefaultLocalFile(formatGeneratedSecretsEnv(secrets));
console.log("");
console.log(`PASS wrote generated project secrets to ${defaultTarget}`);
console.log("No secret values were printed. Keep this file local-only.");
