import { ENTRY } from "@/types";
import { z } from "zod";

import {
  isCanonicalDate,
  noOp,
  type AutomationRuleMutationResult,
  type AutomationRulePlannerContext,
} from "../plannerContracts";

const manualCompletionSourceSchema = z.enum(["quickTap", "exactInput", "calendar"]);

const habitCompletionSourceSchema = z
  .object({
    id: z.string().min(1).max(512),
    entries: z.record(
      z.string(),
      z
        .object({
          value: z.number().finite(),
          source: z.string().optional(),
          loggedAt: z.string().max(64).optional(),
        })
        .passthrough()
    ),
    habitType: z.enum(["boolean", "numerical"]),
    targetType: z.enum(["atLeast", "atMost"]),
    targetValue: z
      .number()
      .finite()
      .min(0)
      .max(Number.MAX_SAFE_INTEGER / 1000),
    isArchived: z.boolean(),
  })
  .passthrough();

const planningEventSchema = z
  .object({
    id: z.string().min(1).max(512),
    date: z.string(),
    source: z.enum(["manual", "habit", "task", "google"]).optional(),
    habitId: z.string().min(1).max(512).optional(),
    isAutoGenerated: z.boolean().optional(),
    isEditable: z.boolean().optional(),
    completed: z.boolean().optional(),
    completedAt: z.number().int().min(0).max(Number.MAX_SAFE_INTEGER).optional(),
  })
  .passthrough();

const planningEventsSchema = z.array(planningEventSchema);

function parseCompletionRevision(revision: string): {
  date: string;
  loggedAt: string;
} | null {
  const match = /^completion:(\d{4}-\d{2}-\d{2}):loggedAt:(.+)$/u.exec(revision);
  if (!match || !isCanonicalDate(match[1])) return null;
  const timestamp = Date.parse(match[2]);
  if (
    !Number.isSafeInteger(timestamp) ||
    timestamp < 0 ||
    new Date(timestamp).toISOString() !== match[2]
  ) {
    return null;
  }
  return { date: match[1], loggedAt: match[2] };
}

function isExplicitManualCompletion(
  source: z.infer<typeof habitCompletionSourceSchema>,
  date: string,
  loggedAt: string
): boolean {
  const entry = source.entries[date];
  if (
    !entry ||
    entry.loggedAt !== loggedAt ||
    !manualCompletionSourceSchema.safeParse(entry.source).success
  ) {
    return false;
  }
  if (source.habitType === "boolean") return entry.value === ENTRY.YES_MANUAL;
  if (entry.value === ENTRY.UNKNOWN || entry.value === ENTRY.SKIP) return false;
  const realValue = entry.value / 1000;
  return source.targetType === "atMost"
    ? entry.value >= 0 && realValue <= source.targetValue
    : source.targetValue > 0 && entry.value > 0 && realValue >= source.targetValue;
}

export function planHabitToPlanningMutation({
  input,
}: AutomationRulePlannerContext): AutomationRuleMutationResult {
  const sourceRecord = habitCompletionSourceSchema.safeParse(input.sourceRecord);
  const completion = parseCompletionRevision(input.source.revision);
  if (
    !sourceRecord.success ||
    !completion ||
    sourceRecord.data.id !== input.source.id ||
    Date.parse(completion.loggedAt) !== input.source.committedAt ||
    !isExplicitManualCompletion(sourceRecord.data, completion.date, completion.loggedAt)
  ) {
    return noOp("SOURCE_INVALID");
  }
  if (sourceRecord.data.isArchived) return noOp("TARGET_INACTIVE");

  const mappedEventId = input.preference.planningHabitMappings[input.source.id];
  if (!mappedEventId) return noOp("MAPPING_MISSING");
  if (input.target.value === null) return noOp("TARGET_MISSING");

  const events = planningEventsSchema.safeParse(input.target.value);
  if (!events.success || !Array.isArray(input.target.value)) return noOp("SOURCE_INVALID");
  const mappedIndexes = events.data.flatMap((event, index) =>
    event.id === mappedEventId ? [index] : []
  );
  if (mappedIndexes.length === 0) return noOp("TARGET_MISSING");
  if (mappedIndexes.length !== 1) return noOp("SOURCE_INVALID");

  const mappedIndex = mappedIndexes[0];
  const mappedEvent = events.data[mappedIndex];
  if (
    mappedEvent.source !== "habit" ||
    mappedEvent.habitId !== input.source.id ||
    mappedEvent.isAutoGenerated !== true ||
    mappedEvent.isEditable !== false
  ) {
    return noOp("TARGET_NOT_AUTOMATION_OWNED");
  }
  if (mappedEvent.date !== completion.date) return noOp("TARGET_INACTIVE");
  const originalMappedEvent = input.target.value[mappedIndex];
  if (
    !originalMappedEvent ||
    Array.isArray(originalMappedEvent) ||
    typeof originalMappedEvent !== "object"
  ) {
    return noOp("SOURCE_INVALID");
  }

  return {
    kind: "mutation",
    after: input.target.value.map((event, index) =>
      index === mappedIndex
        ? {
            ...originalMappedEvent,
            completed: true,
            completedAt: input.source.committedAt,
          }
        : event
    ),
  };
}
