import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const migrationPath = join(
  process.cwd(),
  "supabase/migrations/20260808000000_automation_transaction_ledger.sql",
);
const migration = existsSync(migrationPath) ? readFileSync(migrationPath, "utf8") : "";

function expectFunction(name: string) {
  expect(migration).toMatch(
    new RegExp(`CREATE\\s+OR\\s+REPLACE\\s+FUNCTION\\s+public\\.${name}\\s*\\(`, "i"),
  );
}

function functionSql(name: string): string {
  const start = migration.search(
    new RegExp(`CREATE\\s+OR\\s+REPLACE\\s+FUNCTION\\s+public\\.${name}\\s*\\(`, "i"),
  );
  if (start < 0) return "";
  const end = migration.indexOf("\n$$;", start);
  return end < 0 ? migration.slice(start) : migration.slice(start, end + 4);
}

describe("automation transaction migration contract", () => {
  it("creates only additive owner-bound ledger, mutation, revision, history and preference tables", () => {
    for (const table of [
      "automation_preferences",
      "automation_history_state",
      "automation_transactions",
      "automation_mutations",
      "automation_record_revisions",
      "automation_history_tombstones",
    ]) {
      expect(migration).toMatch(new RegExp(`CREATE\\s+TABLE\\s+public\\.${table}`, "i"));
      expect(migration).toMatch(
        new RegExp(`ALTER\\s+TABLE\\s+public\\.${table}\\s+ENABLE\\s+ROW\\s+LEVEL\\s+SECURITY`, "i"),
      );
      expect(migration).toMatch(
        new RegExp(`REVOKE\\s+ALL\\s+ON\\s+TABLE\\s+public\\.${table}[^;]+authenticated`, "i"),
      );
    }

    expect(migration).not.toMatch(/DROP\s+TABLE|TRUNCATE|DISABLE\s+ROW\s+LEVEL\s+SECURITY/i);
  });

  it("server-linearizes preference enable and disable while blocking the legacy generic key", () => {
    expectFunction("get_automation_preference");
    expectFunction("set_automation_preference");
    expectFunction("revoke_automation_preference");
    expectFunction("reject_reserved_automation_setting");
    expect(migration).toContain("zenflow-connected-records-preferences");
    expect(migration).toMatch(/BEFORE\s+INSERT\s+OR\s+UPDATE\s+OR\s+DELETE\s+ON\s+public\.user_settings/i);
    expect(migration).toMatch(/server_revision\s*=\s*server_revision\s*\+\s*1/i);
    expect(migration).toMatch(/gen_random_uuid\s*\(\s*\)/i);
    expect(migration).toMatch(/FOR\s+UPDATE/i);
    expect(migration).toMatch(
      /automation\.connected-records\.v1'[\s\S]+false[\s\S]+0[\s\S]+false/i,
    );
  });

  it("atomically maps dedicated planning blocks and returns their authoritative revision", () => {
    expectFunction("set_automation_preference_with_planning");
    const planning = functionSql("set_automation_preference_with_planning");
    expect(planning).toContain("p_planning_blocks");
    expect(planning).toContain("p_device_id");
    expect(planning).toContain("zenflow-schedule-events");
    expect(planning).toMatch(/source[^;]+habit/i);
    expect(planning).toMatch(/isAutoGenerated/i);
    expect(planning).toMatch(/isEditable/i);
    expect(planning).toMatch(/FOR\s+UPDATE/i);
    expect(planning).toMatch(/INSERT\s+INTO\s+public\.user_settings/i);
    expect(planning).toMatch(/automation_record_revisions/i);
    expect(planning).toMatch(/scheduleRevision/i);
    expect(planning).toMatch(/scheduleEvents/i);
    expect(planning).toMatch(
      /INSERT\s+INTO\s+public\.sync_events[\s\S]+['\"]setting['\"][\s\S]+zenflow-schedule-events/i,
    );
  });

  it("never reopens an already completed block when unrelated connected rules are saved", () => {
    const planning = functionSql("set_automation_preference_with_planning");
    expect(planning).toMatch(
      /current_event\.event->'completed'\s*=\s*'true'::jsonb[\s\S]+p_planning_habit_mappings->>old_mapping\.habit_id\s+IS\s+NOT\s+DISTINCT\s+FROM\s+old_mapping\.event_id/i,
    );
    expect(planning).toMatch(
      /jsonb_array_elements\(p_planning_blocks\)[\s\S]+NOT\s+EXISTS[\s\S]+current_completed/i,
    );
  });

  it("guards dedicated-block clock casts behind numeric CASE expressions", () => {
    const planning = functionSql("set_automation_preference_with_planning");

    for (const field of ["startHour", "startMinute", "endHour", "endMinute"]) {
      expect(planning).toMatch(
        new RegExp(
          `CASE\\s+WHEN[\\s\\S]+${field}[\\s\\S]+THEN[\\s\\S]+${field}[\\s\\S]+::integer[\\s\\S]+END\\s+AS\\s+${field.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)}`,
          "i",
        ),
      );
    }
    expect(planning).not.toMatch(
      /OR\s+\(item\.block->>'(?:startHour|startMinute|endHour|endMinute)'\)::integer/i,
    );
  });

  it("recomputes a canonical source key and never trusts caller-supplied ownership", () => {
    expectFunction("automation_canonical_json");
    expectFunction("automation_source_key");
    expect(migration).toMatch(/extensions\.digest/i);
    expect(migration).toMatch(/SELECT\s+auth\.uid\s*\(\s*\)/i);
    expect(migration).toMatch(/sourceKey/i);
    expect(migration).toMatch(/automation_source_key\s*\(/i);
    expect(migration).not.toMatch(/p_owner_user_id|p_user_id\s+uuid/i);
  });

  it("rotates authoritative per-target revisions for manual writes and binds automation tokens", () => {
    expectFunction("capture_automation_record_revision");
    for (const table of ["journal_entries", "moods", "habit_completions", "user_settings"]) {
      expect(migration).toMatch(
        new RegExp(`(?:INSERT|UPDATE|DELETE)[^;]+ON\\s+public\\.${table}`, "i"),
      );
    }
    expect(migration).toContain("zenflow.automation_revision_token");
    expect(migration).toContain("zenflow.automation_transaction_id");
    expect(migration).toMatch(/revision_token/i);
    expect(migration).toMatch(/record_exists/i);
  });

  it("commits one bounded batch only after epoch, generation, source and every before-token CAS", () => {
    expectFunction("commit_automation_transaction");
    expect(migration).toMatch(/jsonb_array_length\s*\([^)]*mutations/i);
    expect(migration).toMatch(/>\s*32/);
    expect(migration).toMatch(/expectedPreferenceRevision/i);
    expect(migration).toMatch(/expectedHistoryGeneration/i);
    expect(migration).toMatch(/consentEpoch/i);
    expect(migration).toMatch(/beforeRevisionToken/i);
    expect(migration).toMatch(/pg_advisory_xact_lock/i);
    expect(migration).toMatch(/ORDER\s+BY[^;]+entityType[^;]+entityId/i);
    expect(migration).toMatch(/automation_apply_mutation\s*\(/i);
    expect(migration).toMatch(/UNIQUE\s*\(\s*user_id\s*,\s*source_key\s*\)/i);
    expect(migration).toMatch(/ALREADY_COMMITTED/);
    expect(migration).toMatch(/TARGET_REVISION_CONFLICT/);
    expect(migration).toMatch(/>=\s*128/);
    expect(migration).toMatch(/8\s*\*\s*1024\s*\*\s*1024/);
    expect(migration).toMatch(
      /IF\s*\(v_mutation->'before'\)\s*=\s*'null'::jsonb\s+THEN[\s\S]{0,400}?IF\s+v_revision_found\s+THEN/i,
    );
    expect(migration).not.toMatch(/IF\s+v_revision_found\s+AND\s+v_revision\.record_exists/i);
  });

  it("rejects a permanently purged deterministic transaction before any mutation", () => {
    const commit = functionSql("commit_automation_transaction");
    expect(commit).toMatch(
      /automation_history_tombstones[\s\S]+purged_transaction_id\s*=\s*v_transaction_id/i,
    );
    expect(commit).toContain("TRANSACTION_PURGED");
    expect(commit.indexOf("automation_history_tombstones")).toBeGreaterThan(-1);
    expect(commit.indexOf("automation_history_tombstones")).toBeLessThan(
      commit.indexOf("automation_apply_mutation"),
    );
  });

  it("undoes only the exact after-token state, is idempotent, and emits permanent delete tombstones", () => {
    expectFunction("undo_automation_transaction");
    expect(migration).toMatch(/expectedServerSequence/i);
    expect(migration).toMatch(/compensatingMutations/i);
    expect(migration).toMatch(/after_revision_token/i);
    expect(migration).toMatch(/ALREADY_UNDONE/);
    expect(migration).toMatch(/automation_history_tombstones/i);
    expect(migration).toMatch(/sync_tombstones/i);
    expect(migration).toMatch(/undo_transaction_id/i);
  });

  it("captures revision-row FOUND before evaluating the projection helper", () => {
    const captures = migration.match(/v_revision_found\s*:=\s*FOUND\s*;/gi) ?? [];
    expect(captures).toHaveLength(2);
    expect(migration).toMatch(/IF\s+v_revision_found\s+THEN/i);
    expect(migration).toMatch(/IF\s+NOT\s+v_revision_found\s+OR\s+NOT\s+v_revision\.record_exists/i);
  });

  it("orders snapshots independently of the legacy cursor and fences both per-item and all-history purge", () => {
    expectFunction("get_automation_history_snapshot");
    expectFunction("purge_automation_history");
    const snapshot = functionSql("get_automation_history_snapshot");
    expect(migration).toMatch(/ORDER\s+BY\s+(?:[a-z_]+\.)?server_sequence/i);
    expect(migration).toMatch(/history_generation\s*=\s*history_generation\s*\+\s*1/i);
    expect(migration).toMatch(/all_history_purged_at/i);
    expect(migration).toMatch(/purged_transaction_id/i);
    expect(snapshot).toMatch(/p_snapshot_token\s+jsonb/i);
    expect(snapshot).toMatch(/p_cursor\s+jsonb/i);
    expect(snapshot).toContain("SNAPSHOT_STALE");
    expect(snapshot).toContain("record_revision_version");
    expect(snapshot).toContain("nextCursor");
    expect(snapshot).toMatch(/LIMIT\s+128/i);
    expect(migration).not.toMatch(/Automation revision snapshot capacity exceeded/i);
    expect(migration).toMatch(
      /record_revision_version\s*=\s*public\.automation_history_state\.record_revision_version\s*\+\s*1/i,
    );
    expect(migration).toMatch(
      /UPDATE\s+public\.automation_record_revisions[\s\S]+transaction_id\s*=\s*NULL/i,
    );
    expect(migration).toMatch(/TRANSACTION_PURGED/);
    expect(migration).toMatch(/IF\s+p_all[\s\S]+UPDATE\s+public\.automation_preferences/i);
    expect(migration).toMatch(/enabled\s*=\s*false[\s\S]+consent_epoch\s*=\s*NULL/i);
    expect(migration).toMatch(/'preference'[\s\S]+automation_preference_payload/i);
  });

  it("makes a per-item purge retry converge through retained tombstones", () => {
    const purge = functionSql("purge_automation_history");
    expect(purge).toMatch(
      /p_transaction_ids[\s\S]+automation_history_tombstones[\s\S]+purged_transaction_id/i,
    );
    expect(purge).toMatch(/cardinality\s*\(\s*v_purged_ids\s*\)/i);
    expect(purge).toMatch(/cardinality\s*\(\s*p_transaction_ids\s*\)/i);
  });

  it("binds purge retries to one caller operation and stores the exact canonical result before returning", () => {
    const purge = functionSql("purge_automation_history");
    expect(purge).toMatch(/p_operation_id\s+uuid/i);
    expect(purge).toMatch(
      /SELECT\s+event\.payload[\s\S]+FROM\s+public\.sync_events[\s\S]+idempotency_key\s*=\s*p_operation_id/i,
    );
    expect(purge).toMatch(/'operationId'\s*,\s*p_operation_id/i);
    expect(purge).toMatch(/'completedAt'\s*,\s*v_now/i);
    expect(purge).toMatch(/'preference'[\s\S]+automation_preference_payload/i);
    expect(purge).toMatch(/RETURN\s+v_result/i);
  });

  it("exposes only authenticated RPC execution and one encrypted automation event per accepted batch", () => {
    for (const name of [
      "get_automation_preference",
      "set_automation_preference",
      "set_automation_preference_with_planning",
      "revoke_automation_preference",
      "commit_automation_transaction",
      "undo_automation_transaction",
      "get_automation_history_snapshot",
      "purge_automation_history",
    ]) {
      expect(migration).toMatch(
        new RegExp(`REVOKE\\s+ALL\\s+ON\\s+FUNCTION\\s+public\\.${name}[^;]+PUBLIC[^;]+anon`, "i"),
      );
      expect(migration).toMatch(
        new RegExp(`GRANT\\s+EXECUTE\\s+ON\\s+FUNCTION\\s+public\\.${name}[^;]+authenticated`, "i"),
      );
    }
    expect(migration).toMatch(/INSERT\s+INTO\s+public\.sync_events/i);
    expect(migration).toContain("automation_transaction");
    expect(migration).toContain("NOTIFY pgrst, 'reload schema';");
  });
});
