import { z } from "zod";

import { logger } from "@/lib/logger";
import { offlineQueue } from "@/lib/offlineQueue";
import { scheduleEventSchema } from "@/lib/schemas";
import { broadcastChange } from "@/lib/syncBroadcast";
import { supabase } from "@/lib/supabaseClient";
import { triggerDataRefresh } from "@/hooks/useIndexedDB";
import { db } from "@/storage/db";
import type { ScheduleEvent } from "@/types";
import { validateSyncOwner } from "@/storage/sync/syncOwner";
import { hashAutomationValue } from "./canonicalJson";
import {
  AUTOMATION_PREFERENCE_SETTING_KEY,
  automationPreferenceSchema,
  automationRecordRevisionStoreRowSchema,
  automationRuleIdSchema,
  type AutomationPreference,
  type AutomationRuleId,
} from "./types";

const SCHEDULE_EVENTS_SETTING_KEY = "zenflow-schedule-events";
const SCHEDULE_REVISION_ROW_ID = "record_revision:setting:zenflow-schedule-events";

const planningBlockSchema = scheduleEventSchema.strict().superRefine((event, ctx) => {
  const invalidTime =
    !Number.isInteger(event.startHour) || event.startHour < 0 || event.startHour > 23 ||
    !Number.isInteger(event.endHour) || event.endHour < 0 || event.endHour > 23 ||
    !Number.isInteger(event.startMinute) || event.startMinute < 0 || event.startMinute > 59 ||
    !Number.isInteger(event.endMinute) || event.endMinute < 0 || event.endMinute > 59 ||
    event.endHour * 60 + event.endMinute <= event.startHour * 60 + event.startMinute;
  if (
    event.id.length > 512 ||
    event.title.length < 1 || event.title.length > 512 ||
    event.color.length < 1 || event.color.length > 128 ||
    !/^\d{4}-\d{2}-\d{2}$/.test(event.date) ||
    event.source !== "habit" ||
    !event.habitId || event.habitId.length > 512 ||
    event.isAutoGenerated !== true ||
    event.isEditable !== false ||
    event.completed === true ||
    event.completedAt !== undefined ||
    invalidTime
  ) {
    ctx.addIssue({
      code: "custom",
      message: "Planning blocks must be bounded, unfinished, generated habit blocks",
    });
  }
});

export type AutomationPreferenceErrorCode =
  | "AUTOMATION_ENABLE_REQUIRES_ONLINE"
  | "AUTOMATION_PREFERENCE_OWNER_UNAVAILABLE"
  | "AUTOMATION_PREFERENCE_SERVER_UNAVAILABLE"
  | "AUTOMATION_PREFERENCE_CONFLICT"
  | "AUTOMATION_PREFERENCE_INVALID_RESPONSE"
  | "AUTOMATION_REVOCATION_PENDING";

export class AutomationPreferenceError extends Error {
  readonly code: AutomationPreferenceErrorCode;

  constructor(code: AutomationPreferenceErrorCode, message: string) {
    super(message);
    this.name = "AutomationPreferenceError";
    this.code = code;
  }
}

const enableInputSchema = z
  .object({
    enabledRuleIds: z.array(automationRuleIdSchema).max(4),
    focusHabitId: z.string().min(1).max(512).nullable(),
    focusMinimumMinutes: z.number().int().min(1).max(1440),
    planningHabitMappings: z.record(z.string().min(1).max(512), z.string().min(1).max(512)),
    planningBlocks: z.array(planningBlockSchema).max(100).default([]),
  })
  .strict()
  .superRefine((value, ctx) => {
    if (new Set(value.enabledRuleIds).size !== value.enabledRuleIds.length) {
      ctx.addIssue({
        code: "custom",
        path: ["enabledRuleIds"],
        message: "Connected-record rule IDs must be unique",
      });
    }
    if (Object.keys(value.planningHabitMappings).length > 100) {
      ctx.addIssue({
        code: "custom",
        path: ["planningHabitMappings"],
        message: "Planning mappings cannot exceed 100",
      });
    }
    const planningEnabled = value.enabledRuleIds.includes("habit.to-planning.v1");
    const mappings = Object.entries(value.planningHabitMappings);
    const mappingEventIds = new Set(mappings.map(([, eventId]) => eventId));
    if (
      (planningEnabled && (mappings.length === 0 || value.planningBlocks.length !== mappings.length)) ||
      (!planningEnabled && (mappings.length > 0 || value.planningBlocks.length > 0)) ||
      mappingEventIds.size !== mappings.length ||
      value.planningBlocks.some(
        (block) => value.planningHabitMappings[block.habitId!] !== block.id,
      )
    ) {
      ctx.addIssue({
        code: "custom",
        path: ["planningHabitMappings"],
        message: "Planning mappings must exactly match the selected dedicated blocks",
      });
    }
  });

export interface AutomationPreferenceEnableInput {
  enabledRuleIds: AutomationRuleId[];
  focusHabitId: string | null;
  focusMinimumMinutes: number;
  planningHabitMappings: Record<string, string>;
  planningBlocks?: ScheduleEvent[];
}

export const automationPreferenceRevocationIntentSchema = z
  .object({
    schemaVersion: z.literal(1),
    requestedAt: z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),
  })
  .strict();

export type AutomationPreferenceRevocationIntent = z.infer<
  typeof automationPreferenceRevocationIntentSchema
>;

type PreferenceRpcName =
  | "get_automation_preference"
  | "set_automation_preference"
  | "set_automation_preference_with_planning"
  | "revoke_automation_preference";

interface PreferenceRpcResult {
  data: unknown;
  error: { code?: string; message?: string } | null;
}

interface PreferenceRpcClient {
  rpc(name: PreferenceRpcName, args?: Record<string, unknown>): PromiseLike<PreferenceRpcResult>;
}

let preferenceIntentVersion = 0;

export function createDisabledAutomationPreference(now = Date.now()): AutomationPreference {
  return automationPreferenceSchema.parse({
    schemaVersion: 1,
    enabled: false,
    serverRevision: 0,
    consentEpoch: null,
    consentedAt: null,
    revokedAt: null,
    revocationPending: false,
    enabledRuleIds: [],
    focusHabitId: null,
    focusMinimumMinutes: 25,
    planningHabitMappings: {},
    updatedAt: now,
  });
}

function getRpcClient(): PreferenceRpcClient {
  if (!supabase) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_SERVER_UNAVAILABLE",
      "Connected-record settings are unavailable until cloud sync is configured",
    );
  }
  return supabase as unknown as PreferenceRpcClient;
}

async function requireOwner(expectedOwnerUserId?: string): Promise<string> {
  const ownerUserId = await validateSyncOwner(
    expectedOwnerUserId,
    "Connected-record preference",
  );
  if (!ownerUserId) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_OWNER_UNAVAILABLE",
      "Sign in before changing connected-record settings",
    );
  }
  return ownerUserId;
}

async function callPreferenceRpc(
  name: PreferenceRpcName,
  args?: Record<string, unknown>,
): Promise<unknown> {
  const client = getRpcClient();
  const result = args === undefined ? await client.rpc(name) : await client.rpc(name, args);
  if (result.error) {
    const code = result.error.code === "40001" || result.error.code === "P0001"
      ? "AUTOMATION_PREFERENCE_CONFLICT"
      : "AUTOMATION_PREFERENCE_SERVER_UNAVAILABLE";
    throw new AutomationPreferenceError(
      code,
      result.error.message || "Connected-record settings could not be confirmed by the server",
    );
  }
  return result.data;
}

function parseServerPreference(value: unknown): AutomationPreference {
  const parsed = automationPreferenceSchema.safeParse(value);
  if (!parsed.success || parsed.data.revocationPending) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_INVALID_RESPONSE",
      "The connected-record settings response was not recognized",
    );
  }
  return parsed.data;
}

const planningPreferenceResponseSchema = z
  .object({
    preference: automationPreferenceSchema,
    scheduleEvents: z.array(scheduleEventSchema).max(4096),
    scheduleRevision: z
      .object({
        recordExists: z.literal(true),
        revisionToken: z.string().uuid(),
        stateHash: z.string().regex(/^sha256:[a-f0-9]{64}$/),
        mutationGeneration: z.number().int().min(1).max(Number.MAX_SAFE_INTEGER),
        transactionId: z.string().uuid().nullable(),
        updatedAt: z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),
      })
      .strict(),
    eventSeq: z.number().int().min(1).max(Number.MAX_SAFE_INTEGER),
  })
  .strict();

async function parsePlanningPreferenceResponse(value: unknown, ownerUserId: string) {
  const parsed = planningPreferenceResponseSchema.safeParse(value);
  if (!parsed.success || parsed.data.preference.revocationPending) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_INVALID_RESPONSE",
      "The connected planning response was not recognized",
    );
  }
  const expectedHash = await hashAutomationValue(parsed.data.scheduleEvents);
  if (expectedHash !== parsed.data.scheduleRevision.stateHash) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_INVALID_RESPONSE",
      "The connected planning revision did not match its schedule",
    );
  }
  return {
    preference: parsed.data.preference,
    scheduleEvents: parsed.data.scheduleEvents,
    scheduleRevision: automationRecordRevisionStoreRowSchema.parse({
      kind: "record_revision",
      id: SCHEDULE_REVISION_ROW_ID,
      schemaVersion: 1,
      ownerUserId,
      entityType: "setting",
      entityId: SCHEDULE_EVENTS_SETTING_KEY,
      ...parsed.data.scheduleRevision,
    }),
    eventSeq: parsed.data.eventSeq,
  };
}

async function persistPreference(preference: AutomationPreference): Promise<void> {
  const parsed = automationPreferenceSchema.parse(preference);
  await db.settings.put({ key: AUTOMATION_PREFERENCE_SETTING_KEY, value: parsed });
}

export async function readAutomationPreference(): Promise<AutomationPreference> {
  const row = await db.settings.get(AUTOMATION_PREFERENCE_SETTING_KEY);
  if (row) {
    const parsed = automationPreferenceSchema.safeParse(row.value);
    if (parsed.success) return parsed.data;
    logger.warn("[Automation] Ignoring an invalid local connected-record preference");
  }
  return createDisabledAutomationPreference();
}

export function mergeAutomationPreference(
  local: AutomationPreference,
  remote: AutomationPreference,
): AutomationPreference {
  if (local.revocationPending) return local;
  if (remote.serverRevision > local.serverRevision) return remote;
  if (local.serverRevision > remote.serverRevision) return local;
  if (local.enabled !== remote.enabled) return local.enabled ? remote : local;
  return remote.updatedAt >= local.updatedAt ? remote : local;
}

function hasQueuedRevocation(ownerUserId: string): boolean {
  return offlineQueue
    .getState()
    .actions.some(
      (action) =>
        action.type === "REVOKE_AUTOMATION_PREFERENCE" &&
        action.ownerUserId === ownerUserId,
    );
}

export async function enableAutomationPreference(
  input: AutomationPreferenceEnableInput,
  expectedOwnerUserId?: string,
): Promise<AutomationPreference> {
  if (!navigator.onLine) {
    throw new AutomationPreferenceError(
      "AUTOMATION_ENABLE_REQUIRES_ONLINE",
      "Connect to the internet to enable connected records",
    );
  }
  const validatedInput = enableInputSchema.parse(input);
  const ownerUserId = await requireOwner(expectedOwnerUserId);

  await offlineQueue.processQueue();
  if (hasQueuedRevocation(ownerUserId)) {
    throw new AutomationPreferenceError(
      "AUTOMATION_REVOCATION_PENDING",
      "Finish the pending connected-record revocation before enabling again",
    );
  }

  let current = await readAutomationPreference();
  if (current.revocationPending) {
    current = await flushAutomationPreferenceRevocation(
      { schemaVersion: 1, requestedAt: current.revokedAt ?? Date.now() },
      ownerUserId,
    );
  }

  const intentVersion = ++preferenceIntentVersion;
  const usesPlanningTransaction =
    validatedInput.enabledRuleIds.includes("habit.to-planning.v1") ||
    current.enabledRuleIds.includes("habit.to-planning.v1") ||
    Object.keys(current.planningHabitMappings).length > 0;
  const rpcArgs = {
      p_expected_server_revision: current.serverRevision,
      p_enabled_rule_ids: validatedInput.enabledRuleIds,
      p_focus_habit_id: validatedInput.focusHabitId,
      p_focus_minimum_minutes: validatedInput.focusMinimumMinutes,
      p_planning_habit_mappings: validatedInput.planningHabitMappings,
  };
  const planningResponse = usesPlanningTransaction
    ? await parsePlanningPreferenceResponse(
        await callPreferenceRpc("set_automation_preference_with_planning", {
          ...rpcArgs,
          p_planning_blocks: validatedInput.planningBlocks,
          p_device_id: await import("@/storage/eventSync").then(({ getPersistentDeviceId }) =>
            getPersistentDeviceId()
          ),
        }),
        ownerUserId,
      )
    : null;
  const response = planningResponse?.preference ?? parseServerPreference(
    await callPreferenceRpc("set_automation_preference", rpcArgs),
  );
  if (
    !response.enabled ||
    response.consentEpoch === null ||
    response.revokedAt !== null ||
    response.serverRevision <= current.serverRevision
  ) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_INVALID_RESPONSE",
      "The server did not confirm a fresh connected-record consent epoch",
    );
  }

  await requireOwner(ownerUserId);
  if (intentVersion !== preferenceIntentVersion) return readAutomationPreference();
  if (planningResponse) {
    await db.transaction("rw", db.settings, db.automationTransactions, async () => {
      await db.settings.bulkPut([
        { key: AUTOMATION_PREFERENCE_SETTING_KEY, value: response },
        { key: SCHEDULE_EVENTS_SETTING_KEY, value: planningResponse.scheduleEvents },
      ]);
      await db.automationTransactions.put(planningResponse.scheduleRevision);
    });
    broadcastChange("settings", planningResponse.eventSeq);
    try {
      await triggerDataRefresh();
    } catch (error) {
      logger.warn("[Automation] Connected planning saved but mounted data refresh was deferred", error);
    }
  } else {
    await persistPreference(response);
  }
  return response;
}

async function enqueueRevocation(
  intent: AutomationPreferenceRevocationIntent,
  ownerUserId: string,
): Promise<void> {
  await offlineQueue.enqueue(
    "REVOKE_AUTOMATION_PREFERENCE",
    AUTOMATION_PREFERENCE_SETTING_KEY,
    intent,
    { expectedOwnerUserId: ownerUserId, priority: "critical" },
  );
}

export async function revokeAutomationPreference(
  expectedOwnerUserId?: string,
  requestedAt = Date.now(),
): Promise<{ status: "completed" | "pending"; preference: AutomationPreference }> {
  const ownerUserId = await requireOwner(expectedOwnerUserId);
  preferenceIntentVersion += 1;
  const current = await readAutomationPreference();
  const effectiveRequestedAt = Math.max(requestedAt, current.consentedAt ?? 0);
  const localRevocation = automationPreferenceSchema.parse({
    ...current,
    enabled: false,
    consentEpoch: null,
    revokedAt: effectiveRequestedAt,
    revocationPending: true,
    updatedAt: effectiveRequestedAt,
  });
  const intent = automationPreferenceRevocationIntentSchema.parse({
    schemaVersion: 1,
    requestedAt: effectiveRequestedAt,
  });

  await persistPreference(localRevocation);
  if (!navigator.onLine) {
    await enqueueRevocation(intent, ownerUserId);
    return { status: "pending", preference: localRevocation };
  }

  try {
    const accepted = await flushAutomationPreferenceRevocation(intent, ownerUserId);
    return { status: "completed", preference: accepted };
  } catch (error) {
    logger.warn("[Automation] Connected-record revocation is queued for retry", error);
    await enqueueRevocation(intent, ownerUserId);
    return { status: "pending", preference: localRevocation };
  }
}

export async function flushAutomationPreferenceRevocation(
  rawIntent: AutomationPreferenceRevocationIntent,
  expectedOwnerUserId?: string,
): Promise<AutomationPreference> {
  automationPreferenceRevocationIntentSchema.parse(rawIntent);
  const ownerUserId = await requireOwner(expectedOwnerUserId);
  const current = await readAutomationPreference();
  if (!current.revocationPending && !current.enabled) return current;

  const intentVersion = preferenceIntentVersion;
  const response = parseServerPreference(
    await callPreferenceRpc("revoke_automation_preference"),
  );
  if (response.enabled || response.consentEpoch !== null || response.revokedAt === null) {
    throw new AutomationPreferenceError(
      "AUTOMATION_PREFERENCE_INVALID_RESPONSE",
      "The server did not confirm that connected records are disabled",
    );
  }

  await requireOwner(ownerUserId);
  if (intentVersion !== preferenceIntentVersion) return readAutomationPreference();
  await persistPreference(response);
  return response;
}

export async function refreshAutomationPreference(
  expectedOwnerUserId?: string,
): Promise<AutomationPreference> {
  const ownerUserId = await requireOwner(expectedOwnerUserId);
  const local = await readAutomationPreference();
  if (local.revocationPending) {
    if (!navigator.onLine) return local;
    try {
      return await flushAutomationPreferenceRevocation(
        { schemaVersion: 1, requestedAt: local.revokedAt ?? Date.now() },
        ownerUserId,
      );
    } catch (error) {
      logger.warn("[Automation] Pending connected-record revocation is not yet confirmed", error);
      return local;
    }
  }

  const remote = parseServerPreference(await callPreferenceRpc("get_automation_preference"));
  await requireOwner(ownerUserId);
  const merged = mergeAutomationPreference(local, remote);
  await persistPreference(merged);
  return merged;
}
