/**
 * Custom Service Worker with Background Sync support
 *
 * P1 Fix [WEB]: Enables sync even after browser is closed
 * Uses Workbox BackgroundSyncQueue for reliable offline sync
 */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { setCacheNameDetails } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Set cache name prefix
setCacheNameDetails({
  prefix: 'zenflow',
  suffix: 'v1',
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Background Sync Queue for offline actions
// P0 Fix [WEB]: Continue processing queue even if individual requests fail
const bgSyncPlugin = new BackgroundSyncPlugin('zenflow-offline-queue', {
  maxRetentionTime: 24 * 60, // Retry for max of 24 hours (in minutes)
  onSync: async ({ queue }) => {
    let entry;
    let successCount = 0;
    let failCount = 0;
    const failedEntries: Array<{ request: Request; timestamp?: number }> = [];

    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request);
        successCount++;
        console.log('[SW] Background sync: request succeeded', entry.request.url);
      } catch (error) {
        failCount++;
        console.error('[SW] Background sync: request failed, will retry later', entry.request.url, error);
        // Store failed entry to re-add after processing
        failedEntries.push(entry);
        // P0 Fix: Continue processing remaining items instead of throwing
      }
    }

    // Re-add failed entries to the queue for retry
    for (const failedEntry of failedEntries) {
      await queue.unshiftRequest(failedEntry);
    }

    console.log(`[SW] Background sync complete: ${successCount} succeeded, ${failCount} failed`);

    // Only throw if ALL requests failed (this triggers Workbox to retry later)
    if (successCount === 0 && failCount > 0) {
      throw new Error(`All ${failCount} sync requests failed, will retry`);
    }
  },
});

// Cache Supabase Storage (public assets only)
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/storage/v1/object/public/'),
  new CacheFirst({
    cacheName: 'supabase-storage',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// Cache Google Fonts stylesheets
registerRoute(
  ({ url }) => url.hostname === 'fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache Google Fonts webfonts
registerRoute(
  ({ url }) => url.hostname === 'fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Supabase API calls - NetworkFirst with Background Sync fallback
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') &&
    (url.pathname.includes('/rest/') || url.pathname.includes('/auth/')),
  new NetworkFirst({
    cacheName: 'supabase-api',
    plugins: [
      bgSyncPlugin,
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes cache for API responses
      }),
    ],
    networkTimeoutSeconds: 10,
  }),
  'POST'
);

// Handle navigation requests
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 24 * 60 * 60, // 1 day
      }),
    ],
  })
);

// Listen for sync events (triggered when coming back online)
self.addEventListener('sync', (event) => {
  console.log('[SW] Sync event received:', event.tag);

  if (event.tag === 'zenflow-sync') {
    // Notify clients to process their offline queue
    event.waitUntil(
      self.clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({ type: 'SYNC_REQUESTED' });
        });
      })
    );
  }
});

// Listen for messages from the main app
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  if (event.data?.type === 'REGISTER_SYNC') {
    // Register a sync event (will fire when online)
    self.registration.sync?.register('zenflow-sync').catch((err) => {
      console.warn('[SW] Background sync registration failed:', err);
    });
  }
});

// Log service worker lifecycle
self.addEventListener('install', () => {
  console.log('[SW] Installing...');
});

self.addEventListener('activate', (event) => {
  console.log('[SW] Activating...');
  event.waitUntil(self.clients.claim());
});

console.log('[SW] Service Worker loaded');
