/// <reference lib="webworker" />
/**
 * Custom Service Worker with Background Sync support
 *
 * P1 Fix [WEB]: Enables sync even after browser is closed
 * Uses Workbox BackgroundSyncQueue for reliable offline sync
 */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
// REMOVED: BackgroundSyncPlugin - POST caching was causing "Request body already used" errors
// import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { setCacheNameDetails } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

// Set cache name prefix
setCacheNameDetails({
  prefix: 'zenflow',
  suffix: 'v1',
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// REMOVED: Background Sync Queue - POST caching was causing "Request body already used" errors
// The app uses its own offline queue system (src/lib/offlineQueue.ts) instead

// Cache Supabase Storage (public assets only)
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/storage/v1/object/public/'),
  new CacheFirst({
    cacheName: 'supabase-storage',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// Cache Google Fonts stylesheets
registerRoute(
  ({ url }) => url.hostname === 'fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache Google Fonts webfonts
registerRoute(
  ({ url }) => url.hostname === 'fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// REMOVED: Supabase POST caching (P1 Fix)
// POST requests should NOT be cached/synced at Service Worker level because:
// 1. POST request bodies can only be read once - clone() fails after consumption
// 2. POST requests have side effects and shouldn't be replayed automatically
// 3. The app has its own offline queue system (src/lib/offlineQueue.ts)
// Error was: "Failed to execute 'clone' on 'Request': Request body is already used"

// Handle navigation requests
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 24 * 60 * 60, // 1 day
      }),
    ],
  })
);

// Listen for sync events (triggered when coming back online)
self.addEventListener('sync', (event) => {
  console.log('[SW] Sync event received:', event.tag);

  if (event.tag === 'zenflow-sync') {
    // Notify clients to process their offline queue
    event.waitUntil(
      self.clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({ type: 'SYNC_REQUESTED' });
        });
      })
    );
  }
});

// Listen for messages from the main app
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    console.log('[SW] Skip waiting requested');
    self.skipWaiting();
  }

  if (event.data?.type === 'CLEAR_CACHES') {
    // Clear all caches when app detects version mismatch
    console.log('[SW] Clear caches requested');
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            console.log('[SW] Deleting cache:', cacheName);
            return caches.delete(cacheName);
          })
        );
      })
    );
  }

  if (event.data?.type === 'REGISTER_SYNC') {
    // Register a sync event (will fire when online)
    self.registration.sync?.register('zenflow-sync').catch((err) => {
      console.warn('[SW] Background sync registration failed:', err);
    });
  }
});

// Log service worker lifecycle
self.addEventListener('install', () => {
  console.log('[SW] Installing...');
});

self.addEventListener('activate', (event) => {
  console.log('[SW] Activating...');
  event.waitUntil(self.clients.claim());
});

console.log('[SW] Service Worker loaded');
