import { readFileSync } from "node:fs";
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import type { Translations } from "@/i18n/translations";
import type { ScheduleEvent } from "@/types";
import { AddEventModal } from "../AddEventModal";
import { EventDetailsModal } from "../EventDetailsModal";
import { EventCard3D } from "../ScheduleVisuals";
import { TimelineDayColumn } from "../TimelineDayColumn";

const androidBackRegistration = vi.hoisted(() => ({
  enabled: false,
  onBack: null as null | (() => void),
}));

vi.mock("@/contexts/LanguageContext", () => ({
  useLanguage: () => ({
    language: "en",
    t: {
      close: "Close",
      completed: "Completed",
      scheduleCompletedAt: "Completed at",
      habitReminder: "Habit reminder",
      habitEventExplanation: "Edit the habit to change this block.",
    },
  }),
}));

vi.mock("@/hooks/useShouldAnimate", () => ({ useShouldAnimate: () => false }));
vi.mock("@/hooks/useBackHandler", () => ({
  useBackHandler: (enabled: boolean, onBack: () => void) => {
    androidBackRegistration.enabled = enabled;
    androidBackRegistration.onBack = onBack;
  },
}));
vi.mock("@/components/stats", () => ({ ParticleBackground: () => null }));

const completedEvent: ScheduleEvent = {
  id: "habit-h1-2026-08-09-0",
  title: "Read",
  startHour: 9,
  startMinute: 0,
  endHour: 9,
  endMinute: 30,
  color: "#334455",
  date: "2026-08-09",
  source: "habit",
  habitId: "h1",
  isAutoGenerated: true,
  isEditable: false,
  completed: true,
  completedAt: Date.parse("2026-08-09T09:10:00.000Z"),
};

describe("schedule completed state", () => {
  it("gives the timeline card a non-color completed name and never marks it current", () => {
    render(
      <TimelineDayColumn
        date="2026-08-09"
        dayOffset={0}
        dayEvents={[completedEvent]}
        isDayToday
        isDaySelected
        currentHour={9}
        currentTimePositionPercent={40}
        language="en"
        t={{ night: "Night", morning: "Morning", afternoon: "Afternoon", evening: "Evening", completed: "Completed" } as Translations}
        onEventClick={() => undefined}
        isEventCurrent={() => true}
      />,
    );

    const card = screen.getByRole("button", { name: "Read — Completed" });
    expect(card).toHaveAttribute("data-completed", "true");
    expect(card).toHaveAttribute("data-current", "false");
    expect(screen.getByTestId("schedule-event-completed-icon")).toBeInTheDocument();
  });

  it("shows a localized completed timestamp in details with a 48px close target", () => {
    render(<EventDetailsModal event={completedEvent} onClose={() => undefined} />);

    expect(screen.getByText("09:00 - 09:30")).toHaveAttribute("dir", "ltr");
    expect(screen.getByRole("status")).toHaveTextContent("Completed at");
    expect(screen.getByRole("status")).toHaveClass("text-foreground");
    expect(screen.getByText("Habit reminder")).toHaveClass("text-foreground");
    expect(screen.getByRole("button", { name: "Close" })).toHaveClass("min-h-[48px]");
  });

  it("owns Android Back while details are visible and routes it only to close", () => {
    const onClose = vi.fn();
    render(<EventDetailsModal event={completedEvent} onClose={onClose} />);

    expect(androidBackRegistration.enabled).toBe(true);
    androidBackRegistration.onBack?.();
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it("portals schedule dialogs to the viewport root above the V2 drawer trigger", () => {
    render(
      <AddEventModal
        selectedDate="2026-08-11"
        allDates={["2026-08-11"]}
        onClose={() => undefined}
        onAdd={() => undefined}
        forceDark
      />,
    );

    const addEventDialog = screen.getByRole("dialog", { name: "Add Event" });
    expect(addEventDialog.parentElement).toBe(document.body);
    expect(addEventDialog).toHaveClass("dark");

    render(<EventDetailsModal event={completedEvent} onClose={() => undefined} forceDark />);

    const eventDetailsDialog = screen.getByRole("dialog", { name: "Read" });
    expect(eventDetailsDialog.parentElement).toBe(document.body);
    expect(eventDetailsDialog).toHaveClass("dark");
  });

  it("routes decorative schedule motion through the shared reduced-motion gate", () => {
    const source = readFileSync("src/components/schedule/ScheduleVisuals.tsx", "utf8");
    const details = readFileSync("src/components/schedule/EventDetailsModal.tsx", "utf8");
    expect(source).toContain('useShouldAnimate');
    expect(details).toContain('useShouldAnimate');
  });

  it("renders the standalone card with the same accessible completed contract", () => {
    render(<EventCard3D event={completedEvent} isCurrent onClick={() => undefined} />);
    expect(screen.getByRole("button", { name: "Read — Completed" })).toHaveAttribute(
      "data-current",
      "false",
    );
  });
});
